/**
 * EN — backcast
 * @generated by scripts/split-locales.js
 */
registerLocale('en', {
    backcastPage: {
        history: {
            accent: 'var(--color-backcast)',
            founderLabel: 'Founders',
            founder: 'John B. Robinson & Thomas L. Dreborg',
            yearLabel: 'Year',
            year: 'Late 1970s — 1982',
            institution: 'Swedish Energy Commission · UBC',
            title: 'Origins of Energy Backcasting',
            origin: 'Thomas Dreborg applied backcasting at Sweden\'s Energy Commission in the 1970s for alternative energy policy. John B. Robinson formalized the method in <em>Energy Backcasting: A Proposed Method of Policy Analysis</em> (<em>Energy Policy</em>, 1982), reframing energy planning at UBC from trend prediction to designing desirable futures.',
            problemLabel: 'Problem',
            problem: 'Forecasting can extend past trends but cannot design <strong>desirable alternative energy futures</strong>.',
            useLabel: 'Landmark applications',
            applications: 'Sweden\'s 1970s energy planning, net-zero transition (2045), Vancouver\'s Livable Region Plan, and EU long-term energy scenarios.'
        },

        heroTag: 'John B. Robinson',
        heroTitle: 'Strategic Backcasting',
        heroSub: 'Start from a normative future and work backward — mapping policies, barriers, and practical steps needed from today.',

        methodologyTag: 'Transition Framework',
        methodologyTitle: 'How Backcasting Works',
        methodologyP1: 'Backcasting begins with a <strong>desired future goal</strong>, not today\'s trends. Analysts assume that goal is achieved, then ask what had to change to get there.',
        methodologyP2: 'Four core steps: (1) envision the desired future, (2) gap analysis against the present, (3) design policies and regulations for transition, (4) build an adaptive roadmap of near-, mid-, and long-term actions. Human agency replaces statistical determinism.',

        comparisonTag: 'Comparative Analysis',
        comparisonTitle: 'Backcasting vs. Forecasting',
        comparisonSub: 'Trend-driven planning versus choice-driven planning in large-scale strategy.',
        comparisonIntroP1: 'Robinson introduced backcasting in the late 1970s for alternative energy policy. He argued forecasting — tied to past data — cannot design structural change or normatively desirable futures.',
        comparisonIntroP2: 'Forecasting asks: "What happens if trends continue?" Backcasting asks: "How do we reach a desirable future, and what stands in the way?" It fits energy transition, environmental policy, and urban planning.',
        comparisonHeaders: {
            aspect: 'Dimension',
            forecast: 'Forecasting',
            backcast: 'Backcasting'
        },
        comparisonRows: [
            {
                aspect: 'Time direction',
                forecast: 'Today → future (data extrapolation)',
                backcast: 'Desired future → today (path discovery)'
            },
            {
                aspect: 'Output type',
                forecast: 'Descriptive — probable futures',
                backcast: 'Normative — desirable futures'
            },
            {
                aspect: 'Philosophy',
                forecast: 'Continuity of past trends',
                backcast: 'Human agency and structural change'
            },
            {
                aspect: 'Uncertainty',
                forecast: 'Reduce uncertainty via statistical precision',
                backcast: 'Accept uncertainty; design adaptive paths'
            },
            {
                aspect: 'Best fit',
                forecast: 'Short-term linear trends with rich data',
                backcast: 'Long-term structural crises and systemic gaps'
            }
        ],

        swedenTitle: 'Case Study: Sweden\'s Path to Net Zero by 2045',
        swedenIntro: 'In 2016 Sweden used backcasting — not trend forecasting — to set "net zero by 2045 and fossil-free transport by 2030," then planned backward from that endpoint.',
        swedenSteps: [
            {
                title: 'Final reverse step (2040–2045)',
                body: 'Ban sales of petrol and diesel cars, deploy heavy electric trucks, and replace coal coke with hydrogen in steelmaking.'
            },
            {
                title: 'Mid-range step (2030–2040)',
                body: 'Decarbonize steel (HYBRIT hydrogen project), electrify freight rail, and launch advanced biofuel certificate markets.'
            },
            {
                title: 'Near-term step (2016–2030)',
                body: 'High carbon tax, EV purchase incentives, and public–private investment in battery manufacturing (Northvolt).'
            }
        ],

        simulatorTag: 'Reverse Pathway Simulator',
        simulatorTitle: 'Normative Transition Scenarios for Iran & Tehran',
        simulatorSub: 'Pick a scenario and explore reverse timeline steps.',
        tabTehran: 'Tehran 2051: Sustainable Megacity',
        tabEnergy: 'Energy Security 2051: Zero Imbalance',

        detailPolicy: 'Policies & Regulatory Requirements',
        detailRisk: 'Challenges & Barriers',
        stepTitlePlaceholder: 'Step title',
        stepYearPlaceholder: 'Time horizon',
        stepDescPlaceholder: 'Strategic actions in this period...',
        stepPolicyPlaceholder: 'Laws, standards, and mandates required...',
        stepRiskPlaceholder: 'Logistical, financial, or technology risks...',
        scenarioTitlePlaceholder: 'Scenario title',
        scenarioDescPlaceholder: 'Scenario overview...',

        workspaceTag: 'Normative Strategy Workshop',
        workspaceTitle: 'Interactive Backcasting Workshop',
        workspaceSub: 'Define your long-term goal and map reverse steps back to today.',
        workspacePanelTitle: 'Backcasting Workshop Panel',
        templateLabel: 'Choose a template',
        templateCustom: 'Custom strategy design',
        templateGreen: 'Green Enterprise Transition',
        templateEdu: 'Smart Higher Education by 2041',
        goalLabel: 'Long-term goal (Future Endpoint)',
        goalPlaceholder: 'e.g. Net-zero factory operations',
        goalDefault: 'Full transition to clean energy and carbon-zero technology',
        yearLabel: 'Target year',
        yearPlaceholder: 'e.g. 2046',
        yearDefault: '2041',
        step3Label: 'Step 3: Far horizon (just before the endpoint)',
        step3Placeholder: 'What are the final prerequisites and big moves?',
        step2Label: 'Step 2: Mid horizon (development & modernization)',
        step2Placeholder: 'What mid-term investments and structural changes are needed?',
        step1Label: 'Step 1: Near horizon (immediate actions today)',
        step1Placeholder: 'What are the first executable steps, budget, and permits?',
        generateBtn: 'Draw Backcasting Roadmap',
        previewTag: 'Workshop Output',
        previewTitle: 'Reverse Roadmap to the Final Goal',
        renderGoalPrefix: 'Final goal (year',
        renderHorizon3: 'Far horizon (Step 3)',
        renderHorizon2: 'Mid horizon (Step 2)',
        renderHorizon1: 'Near horizon & present (Step 1)',
        renderFooter: 'Generated by the Strategic Backcasting Simulator',
        renderGoalFallback: 'Your strategic goal...',
        renderYearFallback: '2051',
        renderH3Fallback: 'Far-horizon details...',
        renderH2Fallback: 'Mid-horizon details...',
        renderH1Fallback: 'Near-horizon details...',
        renderContentFallback: 'Content...'
    },

    bcScenarios: {
        tehran: {
            title: 'Tehran 2051: Resilient, Sustainable Megacity',
            desc: 'Normative ecological transition for the capital — halting land subsidence, electrifying urban transit, and full water/wastewater recycling.',
            steps: [
                {
                    year: '2051',
                    label: 'Final goal',
                    title: 'Smart, ecosystem-based, net-zero metropolis',
                    desc: 'Net-zero transport and suburban industry, 100% water recycling, subsidence halted across Tehran plains via IoT and smart management.',
                    policy: 'Carbon and water footprint standards, carbon penalties, and mandatory zero-nonrecyclable-waste certification for industry.',
                    risk: 'Conflict between city and national governance plus macroeconomic volatility threatening green development funds.'
                },
                {
                    year: '2041',
                    label: 'Step 3: Far horizon',
                    title: 'Full transit electrification & aquifer closure',
                    desc: 'Ban internal-combustion vehicles in Tehran, full metro/bus electrification, complete wastewater network, and seal illegal wells.',
                    policy: 'National ban on fossil-fuel vehicles, EV tax incentives, and strict groundwater extraction limits.',
                    risk: 'Battery and semiconductor supply disruption from geopolitical tension and currency limits.'
                },
                {
                    year: '2031',
                    label: 'Step 2: Mid horizon',
                    title: 'Suburban rail ring & smart water metering',
                    desc: 'Express suburban rail ring, smart meters on legal wells, and industrial shift from groundwater to treated wastewater.',
                    policy: 'Mandate peri-urban industries to use recycled water; preferential tariffs for high energy efficiency.',
                    risk: 'Farmer and orchard resistance to well closures and water reallocation.'
                },
                {
                    year: '2026',
                    label: 'Step 1: Present',
                    title: 'Ecological transition council & import incentives',
                    desc: 'Establish capital ecological transition council, subsidence defense charter, zero-duty electric infrastructure imports, and wastewater-to-agriculture pilots.',
                    policy: 'Plain protection legislation, BOT guidelines for electric transit, and private investment incentives.',
                    risk: 'Inter-agency bureaucracy and inflation limiting infrastructure budget allocation.'
                }
            ]
        },
        energy: {
            title: 'Iran Energy Security 2051: Zero Imbalance',
            desc: 'Eliminate gas and power gaps; power plant efficiency above 55%, heavy industry on green hydrogen, 40% renewable electricity.',
            steps: [
                {
                    year: '2051',
                    label: 'Final goal',
                    title: 'Stable energy security & green power exports',
                    desc: 'No load-shedding, 40% solar/wind power, national smart grid, and renewable electricity exports to neighbors.',
                    policy: 'EU CBAM compliance, pollution penalties, and open renewable energy exchange.',
                    risk: 'Technology sanctions and regional instability blocking cross-border grid links.'
                },
                {
                    year: '2041',
                    label: 'Step 3: Far horizon',
                    title: 'Desert solar megaprojects & hydrogen furnaces',
                    desc: 'Large central desert solar farms, retire low-efficiency gas plants, and shift steel/cement to green hydrogen electric arc furnaces.',
                    policy: 'Fossil fuel tax on inefficient industry, 10-year renewable tax holidays, and private power export rights.',
                    risk: 'Distribution grid unable to move dispersed southern solar to northern industrial demand centers.'
                },
                {
                    year: '2031',
                    label: 'Step 2: Mid horizon',
                    title: 'Green energy exchange & rooftop solar',
                    desc: 'Carbon certificate market, low-interest rooftop solar loans, ban permits without Energy Label A, and combined-cycle upgrades above 50%.',
                    policy: 'Renewable feed-in tariff law and 15% clean-power mandate for high-demand industry.',
                    risk: 'Fossil fuel subsidies making private renewable ROI unattractive.'
                },
                {
                    year: '2026',
                    label: 'Step 1: Present',
                    title: 'National energy transition charter & grid opening',
                    desc: 'Adopt clean energy transition roadmap, end state monopoly on power purchase, and zero-duty solar/wind component imports.',
                    policy: 'Liberalized renewable wheeling rates and foreign investment incentives for solar/wind.',
                    risk: 'Institutional resistance to real decentralization and privatization of distribution.'
                }
            ]
        }
    },

    bcTemplates: {
        'green-tech': {
            goal: 'Organization-wide green tech transition with net-zero carbon and waste across the value chain',
            year: '2046',
            h3: 'Far horizon (2044–2046): circular economy standards, 100% on-site solar, zero supply-chain carbon.',
            h2: 'Mid horizon (2036–2043): low-carbon production lines, industrial water recycling, electric logistics.',
            h1: 'Near horizon (2026–2035): energy audit, green bonds, and corporate sustainability task force.'
        },
        'smart-edu': {
            goal: 'Fully digital university powered by metaverse and generative AI, independent of traditional physical campuses',
            year: '2041',
            h3: 'Far horizon (2039–2041): immersive simulators, end centralized exams, blockchain competency credentials.',
            h2: 'Mid horizon (2031–2038): cloud learning platform, upskill 80% of faculty, convert buildings to innovation hubs.',
            h1: 'Near horizon (2026–2030): AI-ready curricula, pilot VR courses, and phase out paper exams.'
        }
    }
});
