/**
 * EN — cla
 * @generated by scripts/split-locales.js
 */
registerLocale('en', {
    claPage: {
        history: {
            accent: 'var(--color-cla)',
            founderLabel: 'Founder',
            founder: 'Sohail Inayatullah',
            yearLabel: 'Developed',
            year: 'Late 1990s — widely published 1998–2004',
            institution: 'Tamkang University · Metafuture.org',
            title: 'Causal Layered Analysis (CLA)',
            origin: 'Sohail Inayatullah developed CLA in the late 1990s and published it widely through the 2000s via articles, books, and Metafuture workshops. The method moves foresight from surface events toward discourse deconstruction and new metaphor creation.',
            problemLabel: 'Problem it addresses',
            problem: 'Traditional foresight often stops at headlines, statistics, and surface trends (Litany) — missing structural, discursive, and mythic roots.',
            useLabel: 'Notable applications',
            applications: 'Singapore Prime Minister\'s Office (PMO), UNESCO, Taiwan government, and Metafuture workshops worldwide.'
        },
        heroTag: 'Sohail Inayatullah',
        heroTitle: 'Causal Layered Analysis (CLA)',
        heroSub: 'A deep foresight method for breaking surface problems apart, exploring discursive and civilizational roots, and creating alternative metaphors for transformative scenarios.',
        theoryTitle: 'CLA foundations and Foucault\'s genealogy',
        theoryLead: 'CLA starts where surface news stops: when you ask “why is this an issue at all?” and the answer is more than headlines and stats.',
        theoryNarrative: [
            'Sohail Inayatullah built CLA on post-structural thought — especially Michel Foucault\'s <strong>genealogy</strong>. Foucault showed that “truth” is shaped by discourse and power; CLA deconstructs issues layer by layer to reveal hidden assumptions.',
            'Moving from Litany (daily news) to systemic causes, then worldview, and finally myth helps stakeholders escape imposed scenarios. The goal is <strong>transformative alternative metaphors</strong> — not only describing the present.',
            'In practice: see what media say (layer 1), which policies and structures produce that story (layer 2), which beliefs legitimise it (layer 3), and which myth or metaphor holds collective imagination (layer 4). Each layer is deeper, harder to change — and more durable when it does change.'
        ],
        theoryP1: 'CLA, created by Sohail Inayatullah, draws on post-structural thought — especially Michel Foucault\'s <strong>genealogy</strong>. Foucault showed that "truth" is shaped by discourse and power; CLA deconstructs issues layer by layer to reveal hidden assumptions.',
        theoryP2: 'Moving from Litany (daily news) to systemic causes, then worldview, and finally myth helps stakeholders escape imposed scenarios and build <strong>transformative alternative metaphors</strong> to reimagine present and future.',
        pyramidTag: 'CLA pyramid',
        pyramidTitle: 'Four layers — click each level',
        layers: {
            litany: {
                badge: 'Layer 1: The Litany',
                badgeClass: 'l1-badge',
                title: 'The most visible level — daily news and statistics',
                body: 'Issues, trends, and numbers seen in media every day. Information is scattered, often emotional, and lacks historical context. Public reaction tends toward passivity or blame. Power discourses use this layer to steer attention.',
                qLabel: 'Key question:',
                question: 'What do media and public opinion say about this problem?',
                langLabel: 'Dominant language:',
                language: 'Journalism, raw statistics, emotional and reactive tone'
            },
            systemic: {
                badge: 'Layer 2: Social/Systemic Causes',
                badgeClass: 'l2-badge',
                title: 'Technical, economic, historical, and political causes',
                body: 'Structures and policies that produce the Litany layer: laws, institutions, markets, bureaucracy, and feedback loops. Experts and policymakers work here, but deeper assumptions remain unchallenged.',
                qLabel: 'Key question:',
                question: 'Which policies, institutions, and structures created this issue?',
                langLabel: 'Dominant language:',
                language: 'Scientific, political, bureaucratic, systems management'
            },
            worldview: {
                badge: 'Layer 3: Discourse/Worldview',
                badgeClass: 'l3-badge',
                title: 'Mental frameworks and legitimizing discourses',
                body: 'Beliefs and paradigms that legitimize Layer 2 structures — from neoliberalism and positivism to traditionalism and environmentalism. Here the boundaries of "truth" and "natural order" are exposed — Foucault\'s discursive power at work.',
                qLabel: 'Key question:',
                question: 'Which beliefs, ideologies, and discourses support these structures?',
                langLabel: 'Dominant language:',
                language: 'Philosophical, cultural, discourse analysis, deep theory'
            },
            myth: {
                badge: 'Layer 4: Myth/Metaphor',
                badgeClass: 'l4-badge',
                title: 'Collective unconscious, archetypes, and metaphors',
                body: 'The deepest layer: stories, emotions, and metaphors that keep worldviews alive across centuries. Change here is hard, but lasting transformation requires new <strong>metaphors</strong>.',
                qLabel: 'Key question:',
                question: 'Which archetype, story, or metaphor dominates our collective unconscious?',
                langLabel: 'Dominant language:',
                language: 'Artistic, mythic, metaphorical, emotionally visual'
            }
        },
        singapore: {
            title: 'Case study: Singapore waste management & smart transit',
            intro: 'In the early 2010s, Singapore\'s PMO Futures Office used CLA to deconstruct the cultural roots of waste buildup and metro overcrowding:',
            l1Label: 'L1: Litany (headlines)',
            l1Text: 'Metro delays, garbage bags piling in apartments, citizen complaints in media.',
            l2Label: 'L2: Systemic causes',
            l2Text: 'Insufficient budget for more train cars, landfill nearing capacity, weak recycling rules.',
            l3Label: 'L3: Worldview (discourse)',
            l3Text: '"Singapore = luxury international hotel" — citizens as demanding customers, government as pure service provider.',
            l4Label: 'L4: Myth (unconscious)',
            l4Text: 'Hidden metaphor of "temporary hotel guests" — no emotional ownership of shared cleanliness.',
            lesson: '<strong>Transformative metaphor:</strong> Reframing to <strong>"Singapore = shared family garden home"</strong> and a "collaborative sustainability" discourse revived ownership and resolved systemic deadlocks.'
        },
        cases: {
            tag: 'Categorized scenario archive',
            title: 'Causal Layered Analysis case examples',
            sub: 'Explore major issues in themed bundles to reveal the discourses and myths behind each domain.',
            tabGeopolitics: 'Geopolitics & international relations',
            tabNational: 'National & environmental challenges',
            tabSocial: 'Social & identity issues'
        },
        workspace: {
            tag: 'Foresight workshop',
            title: 'Interactive CLA thinking workshop',
            sub: 'Pick a preset issue or write your own, then break it into Inayatullah\'s four-layer pyramid.',
            panelTitle: 'Workshop panel',
            templateLabel: 'Choose a preset problem template:',
            templateCustom: '-- Custom analysis --',
            templateBrainDrain: 'Brain drain & talent exodus',
            templateInflation: 'Inflation & livelihood crisis',
            templateGenerationGap: 'Generational values gap',
            problemLabel: 'Your analysis title:',
            problemPlaceholder: 'e.g. Brain drain...',
            litanyLabel: '1. Litany (surface news & statistics):',
            litanyPlaceholder: 'What headlines or stats repeat every day?',
            systemicLabel: '2. Systemic causes (policies, laws, economy):',
            systemicPlaceholder: 'Which structures, laws, or economic drivers sit behind the scenes?',
            worldviewLabel: '3. Worldview & competing discourses:',
            worldviewPlaceholder: 'Which ideologies legitimize these structures?',
            mythLabel: '4. Hidden myth/metaphor (and new alternative):',
            mythPlaceholder: 'Which unconscious story dominates? What new metaphor could replace it?',
            updateBtn: 'Update layered analysis card',
            previewTag: 'CLA workshop output',
            renderTitleDefault: 'Problem title',
            renderL1: 'Litany',
            renderL2: 'Systemic causes',
            renderL3: 'Worldview',
            renderL4: 'Myth & new metaphor',
            renderPlaceholder: 'Content...',
            footer: 'Built in the Foresight Hub interactive workshop',
            defaultTitle: 'Layered problem analysis',
            defaultLitany: 'Litany layer notes...',
            defaultSystemic: 'Systemic layer notes...',
            defaultWorldview: 'Worldview layer notes...',
            defaultMyth: 'Myth layer notes...'
        }
    },
    claCategories: {
        geopolitics: 'Geopolitics & international relations',
        national: 'National & environmental challenges',
        social: 'Social & identity issues'
    },
    caseStudyTitles: {
        israel: 'Iran & Israel',
        usa: 'Iran & USA',
        water: 'Water crisis in Iran',
        'future-iran': 'Iran\'s core future challenge',
        'brain-drain': 'Brain drain & talent exodus',
        'generation-gap': 'Deep generational gap'
    },
    caseStudies: {
        israel: {
            title: 'Iran & Israel',
            l1: '<ul><li>Headlines: missile defense alerts, UN statements, travel warnings</li><li>Oil and currency swings, naval drills in Hormuz</li><li>Public reaction: war anxiety, panic buying</li></ul>',
            l2: '<ul><li>Arms imbalance and "mutual deterrence"</li><li>Abraham Accords/NATO vs. resistance axis</li><li>Cyber war, layered air defense, great-power interests</li></ul>',
            l3: '<ul><li>Discourse of anti-hegemony and liberation of Quds</li><li>vs. existential Zionist security discourse</li><li>Clash of Western liberal order and multipolar Eurasia</li></ul>',
            l4: '<ul><li>Iranian myth: Ashura, Fereydun vs. Zahhak</li><li>Israeli myth: Holocaust, Masada complex</li><li><strong>Alternative:</strong> from "minefield" to "shared oasis ecosystem"</li></ul>',
            l1_q: 'Litany — surface news & data',
            l2_q: 'Systemic — structures & rules',
            l3_q: 'Worldview — legitimizing discourses',
            l4_q: 'Myth — collective unconscious & transformation'
        },
        usa: {
            title: 'Iran & USA',
            l1: '<ul><li>New OFAC sanctions, mutual diplomatic statements</li><li>Tanker seizures, blocked foreign assets</li><li>Rial drop, inflation, fear of trade isolation</li></ul>',
            l2: '<ul><li>Dollar hegemony and SWIFT control</li><li>No formal diplomacy since 1979</li><li>Congress secondary sanctions, Hormuz strategic role</li></ul>',
            l3: '<ul><li>American exceptionalism and liberal order</li><li>vs. independence and anti-hegemony discourse</li><li>Conflicting definitions of responsibility vs. sovereignty</li></ul>',
            l4: '<ul><li>US myth: lone sheriff against outlaws</li><li>Iranian myth: Kaveh the blacksmith vs. Zahhak</li><li><strong>Alternative:</strong> from "Rome vs. Sassanid war" to "digital Silk Road bridge"</li></ul>',
            l1_q: 'Litany — surface news & data',
            l2_q: 'Systemic — structures & rules',
            l3_q: 'Worldview — legitimizing discourses',
            l4_q: 'Myth — collective unconscious & transformation'
        },
        water: {
            title: 'Water crisis in Iran',
            l1: '<ul><li>Drying lakes (Urmia, Hamun, Bakhtegan)</li><li>Land subsidence, water-rights conflicts, dust storms</li><li>Reaction: blame government, climate despair</li></ul>',
            l2: '<ul><li>Food self-sufficiency in dry plains</li><li>Dam building without EIA, illegal wells</li><li>Low water tariffs, irrigation efficiency under 35%</li></ul>',
            l3: '<ul><li>"Engineer nature" development worldview</li><li>vs. ecological sustainability and local wisdom</li><li>Conflicting definitions of progress</li></ul>',
            l4: '<ul><li>Modern myth: conquering engineer with concrete dams</li><li>Ancient myth: Anahita and Tishtar vs. Apush</li><li><strong>Alternative:</strong> from "bleeding the land dry" to "harmony with desert & qanat"</li></ul>',
            l1_q: 'Litany — surface news & data',
            l2_q: 'Systemic — structures & rules',
            l3_q: 'Worldview — legitimizing discourses',
            l4_q: 'Myth — collective unconscious & transformation'
        },
        'future-iran': {
            title: 'Iran\'s core future challenge',
            l1: '<ul><li>Currency and housing spikes, stock market falls, capital flight</li><li>40%+ inflation, power and gas cuts</li><li>Filtering, slow internet, mass emigration</li></ul>',
            l2: '<ul><li>Rentier oil economy and quasi-state monopolies</li><li>FATF non-compliance, heavy bureaucracy</li><li>Pension fund deficits, chronic budget gaps</li></ul>',
            l3: '<ul><li>"Resistive economy & inward turn" discourse</li><li>vs. "developmentalist global integration"</li><li>Conflict: sovereignty priority vs. growth</li></ul>',
            l4: '<ul><li>Phoenix myth: guaranteed survival after crisis</li><li>Nostalgia for "great imperial civilization"</li><li><strong>Alternative:</strong> "Persian carpet" — diverse threads in one coherent pattern</li></ul>',
            l1_q: 'Litany — surface news & data',
            l2_q: 'Systemic — structures & rules',
            l3_q: 'Worldview — legitimizing discourses',
            l4_q: 'Myth — collective unconscious & transformation'
        },
        'brain-drain': {
            title: 'Brain drain & talent exodus',
            l1: '<ul><li>Migration of thousands of doctors, IT engineers, top graduates</li><li>Embassy queues, hospital staff shortages</li><li>Reaction: regret, normalized emigration</li></ul>',
            l2: '<ul><li>Economic instability, falling purchasing power</li><li>Low pay vs. Gulf neighbors</li><li>Non-merit appointments, filtering, weak research infrastructure</li></ul>',
            l3: '<ul><li>"Sacred national service & loyalty" discourse</li><li>vs. "right to grow and join global science"</li><li>Conflict: duty vs. meritocracy</li></ul>',
            l4: '<ul><li>"Unwanted child" archetype</li><li><strong>Alternative:</strong> Brain Drain → Brain Circulation — transnational science networks</li></ul>',
            l1_q: 'Litany — surface news & data',
            l2_q: 'Systemic — structures & rules',
            l3_q: 'Worldview — legitimizing discourses',
            l4_q: 'Myth — collective unconscious & transformation'
        },
        'generation-gap': {
            title: 'Deep generational gap',
            l1: '<ul><li>Different dress, music, digital lifestyles</li><li>Declining marriage and birth rates, state media losing influence</li><li>Reaction: parental confusion, relational disconnect</li></ul>',
            l2: '<ul><li>Mobile internet and Gen Z global culture</li><li>Rigid formal education, broadcast media monopoly</li><li>Institutions out of sync with networked reality</li></ul>',
            l3: '<ul><li>Patriarchal, collectivist traditional worldview</li><li>vs. individual rights, digital global identity</li><li>Conflict: family authority vs. autonomy</li></ul>',
            l4: '<ul><li>"Two strangers under one roof" myth</li><li><strong>Alternative:</strong> "Intergenerational bridge" — warp of old wisdom, weft of new creativity</li></ul>',
            l1_q: 'Litany — surface news & data',
            l2_q: 'Systemic — structures & rules',
            l3_q: 'Worldview — legitimizing discourses',
            l4_q: 'Myth — collective unconscious & transformation'
        }
    },
    workspaceTemplates: {
        'brain-drain': {
            title: 'Brain drain & talent exodus',
            litany: 'Headlines on elite migration, doctor and pilot shortages, long embassy queues.',
            systemic: 'Economic instability, low pay, non-merit hiring, lack of modern lab facilities.',
            worldview: '"National/religious duty" vs. "individual growth & borderless global science market."',
            myth: '"Unwanted child" myth — alternative: "brain circulation" and transnational science networks.'
        },
        inflation: {
            title: 'Inflation & severe livelihood decline',
            litany: 'Instant dollar/gold swings, shrinking household budgets, rent spikes, record inflation.',
            systemic: 'Money supply expansion, budget deficits, SWIFT isolation, blocked oil revenues.',
            worldview: '"Centralized justice & command economy" vs. "free market & monetary reform."',
            myth: 'Sisyphus myth — alternative: "fiscal discipline & productive domestic economy."'
        },
        'generation-gap': {
            title: 'Deep intergenerational values gap',
            litany: 'Youth dress clashes with norms, different music tastes, parents\' digital loneliness complaints.',
            systemic: 'Fast internet, social networks as reference, ineffective formal education.',
            worldview: '"Preserve traditional ethics & family" vs. "freedom of choice & Gen Z digital identity."',
            myth: '"Invisible wall at home" — alternative: "intergenerational synergy bridge."'
        }
    }
});
