/**
 * EN — common
 * @generated by scripts/split-locales.js
 */
registerLocale('en', {
        lang: { label: 'فارسی', switch: 'FA' },
        nav: {
            home: 'Home',
            about: 'About',
            articles: 'Articles',
            methods: 'Methods',
            fitness: 'Future FITness',
            cla: 'Causal Layered Analysis',
            wheel: 'Futures Wheel',
            backcast: 'Backcasting',
            assess: 'Maturity Assessment',
            menu: 'Menu'
        },
        footer: {
            desc: 'Ali Mansouri\'s teaching portal — 8 foresight modules with interactive workshops, lesson plans, and articles.',
            descBackcast: 'An interactive platform for future readiness and fitness assessment — Rohrbeck FITness, Inayatullah CLA, Glenn Futures Wheel, and Robinson normative Backcasting.',
            descWheel: 'An interactive platform for future readiness and fitness assessment — Rohrbeck FITness, Inayatullah CLA, Glenn Futures Wheel, and Robinson normative Backcasting.',
            role: 'PhD Candidate in Foresight, University of Tehran',
            resume: 'View Resume & Profile',
            copyright: 'Ali Mansouri Foresight Portal — methods, personal brand & articles. All rights reserved.'
        },
        index: {
            badge: 'Strategic Foresight Teaching Lab',
            heroTitle: 'STRATEGIC FORESIGHT<br>PORTAL',
            heroSub: 'Ali Mansouri\'s digital classroom — interactive teaching in foresight, futures studies, and strategic foresight for students, managers, and researchers.',
            presenter: 'Presenter:',
            student: 'PhD Candidate in Foresight',
            overviewTag: 'About this portal',
            overviewTitle: 'What is this site and what methods does it include?',
            overviewP1: '<strong>FORESIGHT HUB</strong> is my teaching and research portal: hands-on foresight learning with digital workshops, lesson plans, founder profiles, and policy/organizational cases. It is also my <strong>personal brand</strong> space for articles and professional profile.',
            overviewP2: 'All methods live in one place — the <strong>Methods</strong> page. Interactive workshops (FITness, CLA, Futures Wheel, Backcasting), lesson modules (Popper Diamond, Six Pillars, Scenarios, Futurpreneurship), and a full catalog of Delphi, Morphological Analysis, Horizon Scanning, and dozens more.',
            overviewP3: 'Click any method in the catalog — interactive ones open the simulator directly; others show description, references, and lesson plans (expanding over time).',
            ctaMethods: 'Browse methods catalog',
            overviewFeatures: [
                { icon: 'play-circle', title: 'Interactive workshops', desc: '4 simulators: FITness, CLA, Futures Wheel, Backcasting' },
                { icon: 'book-open', title: 'Lesson modules', desc: '8+ methods with syllabus, founder photo, readings & assignments' },
                { icon: 'library', title: 'Full catalog', desc: '38+ foresight methods in 7 categories — scanning to planning' },
                { icon: 'newspaper', title: 'Articles & brand', desc: 'Research notes, resume, and Ali Mansouri profile' }
            ],
            citationTitle: 'Academic references:'
        },
        common: {
            close: 'Close',
            readMore: 'Learn more',
            order1: '1st Order',
            order2: '2nd Order',
            order3: '3rd Order',
            clickExplore: 'Click to explore',
            scrollHint: 'Scroll to view the full diagram'
        },
        wheel: {
            hubLabel: 'Climate Change in Iran',
            hubSub: '(Reduced rainfall & rising temperatures)',
            sidebarTitle: 'Consequence Network & Hidden Impacts',
            sidebarSub: 'Select a first-order consequence in the circular network to reveal secondary and tertiary cascading effects.',
            chain2: 'Second-Order Consequences',
            chain3: 'Third-Order Consequences'
        },
        cla: {
            layers: {
                litany: 'Litany',
                systemic: 'Systemic Causes',
                worldview: 'Worldview & Discourse',
                myth: 'Myth & Metaphor'
            }
        },
        radar: {
            defaultTitle: 'Emerging Technology Radar',
            defaultSub: 'Click the glowing dots to view technology details, maturity status, and strategic recommendations.',
            status: 'Radar Status:',
            impact: 'Strategic Impact on Organization:'
        }
    });
