/**
 * EN — common
 * @generated by scripts/split-locales.js
 */
registerLocale('en', {
        lang: { label: 'فارسی', switch: 'FA' },
        nav: {
            home: 'Home',
            about: 'About',
            articles: 'Articles',
            methods: 'Methods',
            fitness: 'Future FITness',
            cla: 'Causal Layered Analysis',
            wheel: 'Futures Wheel',
            backcast: 'Backcasting',
            assess: 'Maturity Assessment',
            menu: 'Menu'
        },
        footer: {
            desc: 'Digital foresight classroom — Ali Mansouri, University of Tehran.',
            descBackcast: 'Digital foresight classroom — Ali Mansouri, University of Tehran.',
            descWheel: 'Digital foresight classroom — Ali Mansouri, University of Tehran.',
            role: 'PhD Candidate in Foresight · University of Tehran',
            resume: 'Resume',
            copyright: '© Ali Mansouri — FORESIGHT HUB'
        },
        index: {
            badge: 'Foresight Teaching Lab',
            heroTitle: 'STRATEGIC FORESIGHT<br>HUB',
            heroSub: 'Ali Mansouri\'s digital classroom — interactive foresight, futures studies, and strategic foresight methods.',
            presenter: 'Instructor:',
            student: 'PhD Candidate in Foresight · University of Tehran',
            overviewTag: 'About this portal',
            overviewTitle: 'What is this site?',
            overviewP1: 'This portal is my <strong>digital classroom</strong> for teaching foresight methods — each with explanation, readings, lesson plans, and interactive workshops where available.',
            overviewP2: 'All methods are on the <strong><a href="methods/">Methods</a></strong> page: from FITness and CLA workshops to Delphi, Morphological Analysis, Horizon Scanning, and dozens more.',
            overviewP3: 'Click any card in the catalog — interactive methods open the simulator directly.',
            ctaMethods: 'Browse all methods',
            overviewFeatures: [
                { icon: 'play-circle', title: 'Interactive workshops', desc: 'FITness · CLA · Futures Wheel · Backcasting' },
                { icon: 'book-open', title: 'Lesson modules', desc: 'Popper Diamond · Six Pillars · Scenarios · Futurpreneurship' },
                { icon: 'library', title: '38+ method catalog', desc: 'Scanning · Delphi · Morphological · Scenarios · Roadmap' },
                { icon: 'graduation-cap', title: 'Ali Mansouri', desc: 'PhD Candidate in Foresight · University of Tehran' }
            ]
        },
        common: {
            close: 'Close',
            readMore: 'Learn more',
            order1: '1st Order',
            order2: '2nd Order',
            order3: '3rd Order',
            clickExplore: 'Click to explore',
            scrollHint: 'Scroll to view the full diagram'
        },
        wheel: {
            hubLabel: 'Climate Change in Iran',
            hubSub: '(Reduced rainfall & rising temperatures)',
            sidebarTitle: 'Consequence Network & Hidden Impacts',
            sidebarSub: 'Select a first-order consequence in the circular network to reveal secondary and tertiary cascading effects.',
            chain2: 'Second-Order Consequences',
            chain3: 'Third-Order Consequences'
        },
        cla: {
            layers: {
                litany: 'Litany',
                systemic: 'Systemic Causes',
                worldview: 'Worldview & Discourse',
                myth: 'Myth & Metaphor'
            }
        },
        radar: {
            defaultTitle: 'Emerging Technology Radar',
            defaultSub: 'Click the glowing dots to view technology details, maturity status, and strategic recommendations.',
            status: 'Radar Status:',
            impact: 'Strategic Impact on Organization:'
        }
    });
