/**
 * EN · common
 * @generated by scripts/split-locales.js
 */
registerLocale('en', {
        lang: { label: 'Persian', switch: 'FA' },
        nav: {
            home: 'Home',
            about: 'About',
            articles: 'Articles',
            methods: 'Foresight Methods',
            cv: 'CV',
            fitness: 'Future FITness',
            cla: 'Causal Layered Analysis',
            wheel: 'Futures Wheel',
            backcast: 'Backcasting',
            assess: 'Maturity Assessment',
            menu: 'Menu'
        },
        footer: {
            desc: 'Ali Mansouri\'s personal space for strategic foresight · methods, workshops, and notes · University of Tehran',
            descBackcast: 'Ali Mansouri\'s personal space for strategic foresight · methods, workshops, and notes · University of Tehran',
            descWheel: 'Ali Mansouri\'s personal space for strategic foresight · methods, workshops, and notes · University of Tehran',
            role: 'PhD candidate, Futures Studies · University of Tehran',
            resume: 'CV',
            copyright: '© Ali Mansouri · FORESIGHT HUB'
        },
        index: {
            badge: 'FORESIGHT HUB',
            heroName: 'Hi, I am Ali Mansouri.',
            heroTitle: 'I connect future scenarios to infrastructure that must come out of the hardest pressure still alive and well.',
            heroSub: 'PhD researcher in Futures Studies at the University of Tehran, and Solutions Architect at Snapp for cloud, Kubernetes, and enterprise AI systems.',
            credentialPhd: 'PhD, Futures Studies · University of Tehran',
            credentialFocus: 'Strategic foresight · emerging technology',
            heroIntroP1: '',
            heroIntroP2: '',
            ctaMethods: 'Foresight Methods'
        },

        common: {
            close: 'Close',
            readMore: 'Learn more',
            order1: '1st Order',
            order2: '2nd Order',
            order3: '3rd Order',
            clickExplore: 'Click to explore',
            scrollHint: 'Scroll to view the full diagram',
            tracks: {
                label: 'Delivery track',
                university: 'University',
                industry: 'Industry & organization',
                workshop: 'Interactive workshop',
                universitySection: 'University track · syllabus and teaching',
                industrySection: 'Industry track · organizational delivery',
                workshopSection: 'Interactive workshop',
                labelRole: 'Role',
                labelJob: 'Job',
                agendaTitle: 'Workshop agenda',
                stakeholdersTitle: 'Stakeholders',
                deliverablesTitle: 'Deliverables',
                workflowTitle: 'Workflow',
                checklistTitle: 'Checklist',
                boardMemoTitle: 'Board memo fields',
                facilitatorTitle: 'Facilitator notes'
            }
        },
        wheel: {
            hubLabel: 'Climate Change in Iran',
            hubSub: '(Reduced rainfall & rising temperatures)',
            sidebarTitle: 'Consequence Network & Hidden Impacts',
            sidebarSub: 'Select a first-order consequence in the circular network to reveal secondary and tertiary cascading effects.',
            chain2: 'Second-Order Consequences',
            chain3: 'Third-Order Consequences'
        },
        cla: {
            layers: {
                litany: 'Litany',
                systemic: 'Systemic Causes',
                worldview: 'Worldview & Discourse',
                myth: 'Myth & Metaphor'
            }
        },
        radar: {
            defaultTitle: 'Emerging Technology Radar',
            defaultSub: 'Click the glowing dots to view technology details, maturity status, and strategic recommendations.',
            status: 'Radar Status:',
            impact: 'Strategic Impact on Organization:'
        }
    });
