/**
 * EN — fitness
 * @generated by scripts/split-locales.js
 */
registerLocale('en', {
    fitnessPage: {
        history: {
            accent: 'var(--color-f)',
            founderLabel: 'Founder',
            founder: 'Professor René Rohrbeck',
            yearLabel: 'Year',
            year: '2010',
            institution: 'Aarhus University / EDHEC Business School',
            title: 'Corporate Foresight: Towards a Maturity Model',
            origin: 'In 2010, René Rohrbeck introduced the first structured model for measuring organizational foresight maturity in the academic book <strong>Corporate Foresight: Towards a Maturity Model</strong>. The work was based on multi-year field studies at large European companies at Aarhus University and later at EDHEC.',
            problemLabel: 'Core Problem',
            problem: 'Organizations could not measure their foresight maturity level, could not justify foresight investment, and foresight outputs were not connected to strategic decisions.',
            useLabel: 'Applications & Evidence',
            applications: 'Deployed at <strong>Siemens</strong> and <strong>Deutsche Telekom</strong>; benchmark studies showed foresight-driven organizations achieved <strong>33% higher profitability</strong> and <strong>200% greater market value growth</strong> than vulnerable competitors.'
        },
        hero: {
            tag: 'Dynamic Capabilities Theory — René Rohrbeck',
            title: 'Organizational Foresight Maturity Model & Future FITness',
            subtitle: 'How organizations move beyond static Future Readiness to dynamic Future FITness — continuous organizational fitness and adaptation to shape tomorrow\'s markets.'
        },
        readiness: {
            tag: 'Foundations of Foresight',
            title: 'What Is Future Readiness?',
            sub: 'Forecasting trends, understanding scenarios, and strategic planning to manage uncertainty.',
            p1: '<strong>Future Readiness</strong> means the ability to anticipate change, understand it deeply, and plan purposeful responses. Rooted in uncertainty management: scanning risks and turning them into major opportunities.',
            p2: 'Today\'s world faces rapid technological change — from generative AI to climate disruption. Organizations and individuals prepared for the future see these shifts as opportunities for leadership and progress, not paralyzing threats.',
            challengeTitle: 'A Challenging Question',
            challengeText: 'Is your organization — or you personally — ready for fundamental future changes? If you wanted to make a change today that builds future fitness, what would your first key step be?',
            fiveElementsTitle: '5 Core Elements of Future Readiness',
            foresightTitle: 'Foresight & Scenario Planning',
            foresightText: 'Foresight means deeply understanding trends and analyzing alternative scenarios. Companies that had piloted remote-work technology before the COVID pandemic adapted to lockdown conditions far faster.',
            agilityTitle: 'Organizational Agility',
            agilityText: 'Agility means fast decision-making and rapid pivoting in response to unexpected conditions. Zoom expanded server infrastructure within weeks during COVID to serve hundreds of millions of new users.',
            sustainabilityTitle: 'The Critical Role of Sustainability in Portfolio Strategy',
            sustainabilityP1: 'Sustainability is more than social responsibility — it is smart business strategy. Aligning with ESG goals reduces climate risk and creates lasting competitive advantage in global markets.',
            sustainabilityP2: 'IKEA committed to 100% recycled and renewable materials by 2030, building customer loyalty and lowering long-term material costs. Tesla (electric vehicles) and Amazon (advanced logistics) secured survival and leadership by investing in long-term trends.',
            globalAppsTitle: 'Global Applications of Future Readiness',
            apps: [
                { label: 'Education (Finland)', text: 'Finland\'s project-based, innovation-focused education system prepares students to solve complex real-world problems of tomorrow.' },
                { label: 'Policy (Singapore)', text: 'Singapore\'s Smart Nation program uses technology to prepare the economy and citizens\' quality of life for the aging challenge.' },
                { label: 'Healthcare (NHS UK)', text: 'Big data analytics and AI for early disease diagnosis and hospital resource optimization.' },
                { label: 'Transport & Crisis (Netherlands & Japan)', text: 'The Netherlands with green transport and Japan with earthquake warning and crisis management systems are national resilience leaders.' }
            ]
        },
        readinessCards: [
            { icon: 'trending-up', title: 'Trend Forecasting & Analysis', desc: 'Analyzing key external trends such as demographic shifts or emerging technologies and their industry impact.', color: 'var(--color-f)' },
            { icon: 'zap', title: 'Rapid Adaptation to Change', desc: 'High agility: extraordinarily fast decision-making and strategic pivoting when facing crises.', color: 'var(--color-i)' },
            { icon: 'lightbulb', title: 'Creativity & Innovation Development', desc: 'Creating new solutions for present and future challenges through process changes or novel products.', color: 'var(--color-t)' },
            { icon: 'graduation-cap', title: 'Continuous Learning Culture', desc: 'Ongoing upskilling and team learning to keep pace with global scientific and technological change.', color: 'var(--color-cla)' },
            { icon: 'cpu', title: 'Smart Technology Use', desc: 'Deploying powerful tools like AI and blockchain for better forecasting, planning, and process execution.', color: 'var(--color-wheel-red)' }
        ],
        fitness: {
            tag: 'Beyond Readiness',
            title: 'What Is Future FITness?',
            sub: 'A theoretical comparison of continuous adaptation and optimization versus traditional strategic readiness.',
            p1: 'While <strong>Future Readiness</strong> focuses on forecasting and preparation, <strong>Future FITness</strong> goes further: the continuous, dynamic ability to maintain optimal performance, adapt constantly, grow, and redefine structures when facing unexpected challenges.',
            p2: 'Professor René Rohrbeck\'s long-term studies at Aarhus University showed that "vigilant and future-fit" companies averaged <strong>33% higher profitability</strong> and <strong>200% greater market value growth</strong> than vulnerable competitors.',
            teeceTitle: 'Alignment with David Teece\'s Dynamic Capabilities',
            teece: [
                { title: 'Sensing', text: 'Continuous identification of change signals, trends, and threats in highly turbulent industry environments (aligned with Kathleen Eisenhardt\'s theory).' },
                { title: 'Seizing', text: 'Capturing new opportunities through agile business model design and investment channels aligned with plausible futures.' },
                { title: 'Transforming', text: 'Continuous renewal of tangible and intangible organizational assets to maintain competitive advantage and environmental alignment.' }
            ],
            dashboardTitle: 'Conceptual Corporate Foresight Maturity Dashboard',
            dashboardP1: 'This dashboard shows the interactive structure of organizational dynamic capabilities. Organizations can assess technological alignment and implement Perceiving, Prospecting, and Probing processes in balanced form.',
            dashboardP2: 'The match between industry turbulence and foresight maturity determines survival and profitability — preventing structural rigidity collapses like Nokia and Kodak.',
            stepsTitle: '5-Step Systematic Process to Achieve Future FITness'
        },
        fitnessSteps: [
            { title: 'Assess Current State', desc: 'Identify internal strengths, weaknesses, opportunities, and threats using a SWOT matrix.' },
            { title: 'Define Future Vision', desc: 'Define desirable futures and set goals based on global trends as a roadmap.' },
            { title: 'Develop Capabilities', desc: 'Invest in R&D (like Apple) to strengthen innovation capacity.' },
            { title: 'Implement & Experiment', desc: 'Test ideas with high flexibility (like Tesla experimenting with different electric vehicle models).' },
            { title: 'Monitor & Continuously Improve', desc: 'Continuously track results from feedback and optimize models (like IKEA on sustainability goals).' }
        ],
        archetypes: {
            tag: 'Rohrbeck\'s Dynamic Typology',
            title: '4 Foresight Maturity Archetypes in Industry',
            sub: 'Organizations are classified into four groups based on how well "foresight thinking maturity" matches "industry change speed and turbulence."',
            vigilant: {
                level: 'Maturity Level 4',
                title: 'Vigilant',
                desc: 'Organizational foresight matches or exceeds industry change speed. Continuous weak-signal monitoring and rapid response.',
                note: '33% higher profitability and 200% greater market value growth',
                detail: {
                    title: 'Vigilant Archetype',
                    alignment: 'High industry turbulence + high strategic foresight maturity (full alignment with transformation)',
                    symptoms: 'Leading organizations with high dynamic capabilities. Per David Teece, they combine continuous Sensing with fast Seizing and ongoing Transforming. Immune to analysis paralysis; they creatively destroy their own product portfolios before competitors do.',
                    reps: 'Nvidia (CUDA platform), Netflix (DVD to streaming and original content).'
                }
            },
            neurotic: {
                level: 'Heterogeneous Maturity',
                title: 'Neurotic',
                desc: 'High foresight capacity but in a slow-changing industry. Leads to over-analysis and false alarm.',
                note: 'Over-development of unused scenarios',
                detail: {
                    title: 'Neurotic Archetype',
                    alignment: 'Low industry turbulence + excessive foresight maturity (imbalance from hyper-sensitivity)',
                    symptoms: 'Over-analysis and decision paralysis. Despite massive investment in technology observatories, they cannot separate signal from noise. Fear-driven culture produces hundreds of parallel scenarios with no operational output, blocking strategic decisions.',
                    reps: 'Traditional oil & gas majors that invested billions in unrelated renewables before market demand materialized.'
                }
            },
            vulnerable: {
                level: 'Maturity Level 2',
                title: 'Vulnerable',
                desc: 'Formal strategic processes but disconnected from change signals. Repeated surprise by disruptive competitor innovations.',
                note: 'Absolute reliance on paper 5-year plans',
                detail: {
                    title: 'Vulnerable Archetype',
                    alignment: 'High industry turbulence + low foresight maturity (strategic danger zone)',
                    symptoms: 'Organizations in turbulent industries without scanning capability. Reliant on linear 5-year planning, interpreting rapid tech change as temporary fluctuations. Cognitive rigidity; they react when market value is destroyed and recovery costs are crippling.',
                    reps: 'Kodak (ignoring digital cameras), Nokia (missing the software touchscreen revolution).'
                }
            },
            danger: {
                level: 'Maturity Level 1',
                title: 'In Danger',
                desc: 'No scanning system in a highly turbulent industry. Facing dissolution or total market share loss.',
                note: 'Severely diminished organizational survival hope',
                detail: {
                    title: 'In Danger Archetype',
                    alignment: 'Low industry turbulence + low foresight maturity (hidden stagnation and decline)',
                    symptoms: 'The silent death archetype — organizations in apparently stable industries with no environmental monitoring. Trapped in long-term stability illusion. The smallest environmental shock (regulatory change or sudden substitute technology) can destroy the business model in seconds.',
                    reps: 'Traditional taxi unions before Uber/Snapp; physical travel agencies before online booking.'
                }
            }
        },
        roles: {
            tag: 'Organizational Innovation Function',
            title: '3 Critical Foresight Roles in Innovation Dynamics',
            sub: 'René Rohrbeck proves foresight must play three roles — initiator, strategist, and opponent — in the innovation value chain.',
            initiator: {
                tab: '1. Initiator Role',
                title: '1. Initiator — Spark of Innovation',
                desc: 'The Initiator operates in the <strong>Perceiving</strong> phase: continuously scanning the external environment, discovering emerging trends, and converting them into initial innovation concepts.',
                duties: [
                    'Launch and maintain technology radars and emerging trend monitoring.',
                    'Identify weak signals of change before they become mainstream.',
                    'Run creative brainstorming workshops to generate novel innovation concepts.'
                ],
                example: '<strong>Deutsche Telekom</strong>\'s foresight unit, monitoring miniature sensors, sparked IoT projects by proposing connecting farmland to the network.'
            },
            strategist: {
                tab: '2. Strategist Role',
                title: '2. Strategist — Investment Portfolio Guide',
                desc: 'The Strategist operates in the <strong>Prospecting</strong> phase: steering innovation investment portfolios based on future scenarios and organizational strategy.',
                duties: [
                    'Develop offensive and defensive foresight scenarios for the industry.',
                    'Draw technology roadmaps to align departments.',
                    'Define shared future visions for the organization.'
                ],
                example: '<strong>Nvidia</strong> leadership analyzed data-processing scenarios and redirected the entire R&D portfolio toward AI data-center architecture.'
            },
            opponent: {
                tab: '3. Opponent Role',
                title: '3. Opponent — Devil\'s Advocate',
                desc: 'The Opponent operates in the <strong>Probing</strong> phase: challenging rigid assumptions, critically evaluating projects, and preventing management confirmation bias.',
                duties: [
                    'Run harsh scenarios to test project survival and resilience.',
                    'Conduct war-gaming to expose internal weaknesses.',
                    'Facilitate creative cannibalization to retire profitable legacy products.'
                ],
                example: 'When <strong>Steve Jobs</strong> launched the iPhone, he opposed the iPod (a top seller) — knowing a competitor would integrate music players into phones if Apple didn\'t.'
            }
        },
        cases: {
            tag: 'Deep Cases: Sensing, Prospecting, Transforming',
            title: 'Responding to Change with Three-Dimensional Dynamic Capability DNA',
            sub: 'Systematic analysis of failures and successes through Sensing, Seizing, and Transforming.',
            netflix: {
                tab: 'Netflix (Continuous Dynamic Evolution)',
                title: 'Netflix — Leader in Dynamic Capability Reinvention',
                scanning: 'In the late 1990s, leadership monitored home internet bandwidth and video compression, recognizing physical DVD obsolescence. This was precise weak-signal sensing.',
                seizing: 'In 2007, launched online streaming. In 2012, allocated major resources to original content (House of Cards) to reduce studio dependency.',
                transforming: 'Fully shifted from internal data centers to cloud (AWS) and continuously redefined around generative AI and deep personalization. Lesson: readiness to destroy current successful revenue models.'
            },
            nvidia: {
                tab: 'Nvidia (Betting on an Invisible Future)',
                title: 'Nvidia — Risky Bet on a Future Computing Paradigm',
                scanning: 'In the early 2000s, Jensen Huang saw parallel GPU architecture had applications beyond game rendering — transformative for scientific computing and AI algorithms.',
                seizing: 'In 2006, heavily invested in developing the CUDA platform. Wall Street repeatedly criticized the project with no market demand, but Nvidia persisted.',
                transforming: 'With deep learning in 2012, Nvidia became the world\'s ready AI hardware-software hub. Huang transformed the company from a graphics card maker to an AI infrastructure giant. Lesson: persistence on long-term differentiating capabilities.'
            },
            nokia: {
                tab: 'Nokia (Structural Rigidity & Systemic Failure)',
                title: 'Nokia — Structural Rigidity & Success Trap',
                scanning: 'Nokia received signals about touchscreens and software ecosystems; they even developed touchscreen tablet prototypes years before the iPhone.',
                seizing: 'Due to the success trap and high button-phone margins, executives kept Symbian. Bureaucracy prevented danger signals from becoming bold decisions.',
                transforming: 'Fear culture and optimistic reporting hid technical weaknesses. Rigid bureaucracy blocked reinvention; Symbian couldn\'t compete with iOS and Android. Nokia lost the mobile market entirely. Lesson: cognitive rigidity can neutralize the best scanning capacity.'
            },
            blockbuster: {
                tab: 'Blockbuster (Fear of Revenue Cannibalization)',
                title: 'Blockbuster — Foresight Sacrificed to Short-Term Shareholders',
                scanning: 'Blockbuster managers tracked Netflix\'s growth and digital distribution, knowing the physical rental model was ending.',
                seizing: 'CEO John Antioco launched an online platform and eliminated late fees — actions aimed at capturing streaming opportunities.',
                transforming: 'Short-term-minded boards fired the CEO due to temporary revenue drops (late fees were 16% of profit), restored fees, and refocused on physical stores — leading to bankruptcy. Lesson: short-term shareholder interests vs. long-term survival investment is the biggest transformation barrier.'
            }
        },
        formula: {
            tag: 'Strategic Acronym',
            title: 'The Three-Part Future FITness Formula',
            sub: 'This model connects foresight (F) to the innovation engine (I) and guarantees transformation (T) as the final outcome.',
            clickPrompt: 'Click any letter above to view details.',
            letterF: 'Foresight',
            letterI: 'Innovation',
            letterT: 'Transformation',
            descF: 'Foresight',
            descI: 'Innovation',
            descT: 'Transformation',
            foresight: {
                badge: 'Foresight',
                title: 'Continuous Scanning & Interpretation of Change Signals',
                body: 'Foresight is the organization\'s systematic ability to monitor the external environment, discover weak signals, and understand trends. This corresponds to <strong>Perceiving</strong> and <strong>Prospecting</strong> in Rohrbeck\'s theory.',
                items: [
                    'Continuous monitoring of macro economic, technological, and political environments.',
                    'Analyzing plausible scenarios and developing roadmaps.',
                    'Preventing strategic surprise from sudden disruptions.'
                ]
            },
            innovation: {
                badge: 'Innovation',
                title: 'Converting Insights into Novel Products & Tools',
                body: 'Innovation is the execution engine of foresight. Ideas become rapid prototypes — corresponding to <strong>Probing</strong> and requiring Initiator, Strategist, and Opponent roles.',
                items: [
                    'Rapid prototyping to test ideas.',
                    'Challenging current assumptions through the Opponent role.',
                    'Launching pilot projects to validate market assumptions.'
                ]
            },
            transformation: {
                badge: 'Transformation',
                title: 'Structural & Cultural Redesign for Long-Term Survival',
                body: 'Transformation is the ultimate goal. Foresight and innovation must change culture, structure, and resource allocation — building new organizational DNA for long-term survival.',
                items: [
                    'Reforming formal structure and reducing bureaucracy for greater agility.',
                    'Embracing continuous learning and reducing fear of failure among staff.',
                    'Continuously aligning dynamic capabilities with emerging technological trends.'
                ]
            }
        },
        rohrbeckDims: {
            tag: 'Rohrbeck Conceptual Framework',
            title: 'Five Dimensions of Organizational Foresight Maturity',
            sub: 'Based on Professor René Rohrbeck\'s longitudinal research, strategic foresight capability is measured and calibrated across five structural dimensions.',
            dims: [
                { level: '1. Information', title: 'Information Sources & Quality', desc: 'Breadth, depth, and quality of environmental scanning; bandwidth of monitored information, scanning beyond current industry boundaries, and early weak-signal discovery.' },
                { level: '2. Methods', title: 'Foresight Methodologies', desc: 'Diversity and effectiveness of tools; regular use of qualitative and quantitative methods (scenario planning, Delphi, technology roadmapping, cross-impact analysis).' },
                { level: '3. People', title: 'Human Capital & Experts', desc: 'Competence, futures literacy, and expert mix; manager training, intelligence networks, staff motivation to share insights, and recruiting foresight talent.' },
                { level: '4. Organization', title: 'Formal Structure & Decision-Making', desc: 'Formal feedback mechanisms and bureaucracy; connecting foresight outputs to strategic planning, R&D budgeting, and administrative flexibility.' },
                { level: '5. Culture', title: 'Uncertainty Acceptance & Innovation', desc: 'Foundational values; tolerance of failure, encouraging creative and non-linear thinking, willingness to creatively cannibalize before competitors, and no fear of voicing change warnings.' }
            ]
        },
        assessment: {
            tag: 'Interactive Assessment Tool',
            title: 'Organizational Foresight Maturity Index',
            sub: 'Based on Rohrbeck\'s five maturity dimensions, assess your organization\'s future fitness and receive strategic analysis.',
            formTitle: 'Foresight Maturity Self-Assessment Questionnaire',
            sliders: {
                info: { label: '1. Information & Scanning', desc: 'Access, monitoring, and analysis of change signals and major external trends in the organization.' },
                methods: { label: '2. Methods & Tools', desc: 'Regular use of scientific foresight methods such as scenario writing, Delphi, and technology radar.' },
                people: { label: '3. People & Expertise', desc: 'Staff skills training, external expert engagement, and organizational participation in futures thinking.' },
                org: { label: '4. Formal Organization', desc: 'Dedicated foresight structures, connecting outputs to board decisions, and independent budgeting.' },
                culture: { label: '5. Organizational Culture', desc: 'Change acceptance, no fear of failure, and intrapreneurship with senior management support.' }
            },
            calculateBtn: 'Calculate Maturity Index',
            resultsTitle: 'Organizational Maturity Analysis',
            resetBtn: 'Re-assess',
            analyzing: 'Analyzing...',
            calculating: 'Calculating...',
            insightTitle: 'Strategic Maturity Interpretation:',
            chartLabel: 'Current Organizational Maturity Level',
            chartLabels: [
                'Information & Scanning',
                'Methods & Tools',
                'People & Expertise',
                'Formal Organization',
                'Organizational Culture'
            ],
            metricsTitle: '5 Operational Future FITness Assessment Metrics',
            scores: {
                fit: {
                    status: 'Future Fit Leader',
                    description: 'Congratulations! Your organization has exceptional dynamic capabilities. You don\'t just predict change — you design innovative business models that redefine your industry\'s future. Keep focusing on open innovation and ecosystem participation.',
                    recs: [
                        'Lead the industry by sharing knowledge and participating in startup ecosystems.',
                        'Invest in high-risk disruptive technologies (quantum and bio-computing).',
                        'Balance optimizing current processes with developing entirely new markets.'
                    ]
                },
                prepared: {
                    status: 'Prepared & Alert',
                    description: 'Your organization performs well in trend scanning and readiness, but still needs stronger Probing processes and cultural transformation. Don\'t just wait for the future — actively create the desired future.',
                    recs: [
                        'Increase rapid prototyping projects to test technology assumptions.',
                        'Delegate more authority to frontline staff for faster decision-making.',
                        'Build a shared foresight language across organizational departments.'
                    ]
                },
                vulnerable: {
                    status: 'Vulnerable to Change',
                    description: 'Warning! Your organization is in the danger zone. Over-reliance on traditional processes and cultural resistance to change threatens survival in market uncertainty. Urgent transformation in information infrastructure and management mindset is required.',
                    recs: [
                        'Immediately launch monthly environmental scanning to identify emerging threats.',
                        'Run foresight thinking and crisis management workshops for leaders.',
                        'Reduce formal bureaucracy to enable rapid market response.'
                    ]
                }
            }
        },
        foresightCards: [
            { icon: 'gauge', title: 'Rapid Adaptation Index', desc: 'Agility Index: speed and effectiveness of product portfolio pivots (like fast product cycles in IT companies).', color: 'var(--color-f)' },
            { icon: 'rocket', title: 'Continuous Innovation Rate', desc: 'Innovation Rate: number and quality of alternative solutions and market leadership (like Tesla\'s annual innovation releases).', color: 'var(--color-f)' },
            { icon: 'shield', title: 'Organizational Resilience', desc: 'Resilience Score: ability to recover quickly after financial and environmental disruptions (like Japan).', color: 'var(--color-f)' },
            { icon: 'users', title: 'Ecosystem Collaboration', desc: 'Collaboration Score: joint value creation with partners and supply chain stakeholders (like Amazon).', color: 'var(--color-f)' },
            { icon: 'book-open', title: 'Organizational Learning', desc: 'L&D Metrics: hours of specialized training and workforce skill upgrades per year (like Google).', color: 'var(--color-f)' }
        ],
        radar: {
            tag: 'Case Study: Deutsche Telekom',
            title: 'Emerging Technology Radar & Strategic Monitoring',
            sub: 'Interactive technology radar simulation to prevent strategic surprise. Click radar dots to load impact analysis and recommendations.',
            defaultTitle: 'Emerging Technology Radar',
            defaultText: 'A strategic tool to prevent surprise in telecommunications and IT. Click the pulsing dots to view details.',
            dtCaseTitle: 'Why Was Deutsche Telekom Selected as Benchmark?',
            dtCaseBody: 'Selecting <strong>Deutsche Telekom</strong> is scientifically grounded. A major part of René Rohrbeck\'s doctoral work and reference book on the foresight maturity model was built directly on multi-year operational study at this telecom giant. It is a successful example of technology radar integration connected to strategic processes and risk reduction.',
            dtChallengesTitle: 'Deployment Challenges & Strategic Solutions',
            dtChallengesBody: '<strong>Resistance to change:</strong> strengthen open culture and change acceptance.<br><strong>Skills gap:</strong> continuous reskilling programs.<br><strong>Open ecosystem complexity:</strong> deploy open, transparent technologies.<br><strong>Short/long-term goal conflict:</strong> separate budgeting and three-horizon innovation model.',
            rings: { scan: 'Scan', assess: 'Assess', trial: 'Trial', adopt: 'Adopt' },
            quadrants: {
                ai: 'AI & Data',
                net: 'Communications Networks',
                comp: 'Emerging Computing & Cloud',
                bio: 'Biotech & Convergent Tech'
            },
            statusLabel: 'Radar Status:',
            impactLabel: 'Strategic Impact on Organization:',
            tech: {
                genai: { title: 'Generative AI', quadrant: 'AI & Data', status: 'Adopt', desc: 'Large language models and image generation models for automated content, code, and workflow optimization.', impact: 'Routine task automation, up to 40% production efficiency gains, and fully personalized user experiences.' },
                agentic: { title: 'Agentic AI', quadrant: 'AI & Data', status: 'Trial', desc: 'Advanced AI systems that receive high-level goals and autonomously design, test, and execute multi-step tasks.', impact: 'Reduced direct human oversight, independent supply chain conflict resolution, and real-time decision processes.' },
                nlp: { title: 'Advanced NLP', quadrant: 'AI & Data', status: 'Adopt', desc: 'Natural language understanding for speech, text, sentiment analysis, and hidden knowledge extraction from documents.', impact: 'True 24/7 support via smart voice assistants and early customer dissatisfaction detection on social media.' },
                '6g': { title: '6G Mobile Communications', quadrant: 'Communications Networks', status: 'Scan', desc: 'Terabit-per-second speeds, microsecond latency, and integration of terrestrial networks with satellites for full global coverage.', impact: 'Foundation for internet of senses, remote collaborative robots, and 3D holographic communications.' },
                iot: { title: 'IoT Ecosystems', quadrant: 'Communications Networks', status: 'Trial', desc: 'Connecting hundreds of millions of smart sensors for data collection from operations, warehouses, and logistics.', impact: 'Energy waste reduction, smart agricultural process monitoring, and improved factory equipment productivity.' },
                quantum: { title: 'Quantum Computing', quadrant: 'Emerging Computing & Cloud', status: 'Assess', desc: 'Using quantum qubits for physical simulations and complex mathematical optimizations beyond classical computers.', impact: 'Faster drug discovery, advanced portfolio optimization, and serious risks to current cybersecurity and encryption.' },
                edge: { title: 'Edge Computing', quadrant: 'Emerging Computing & Cloud', status: 'Adopt', desc: 'Processing data at the source (sensor or camera) instead of sending to central cloud servers to reduce latency and bandwidth.', impact: 'Instant autonomous vehicle navigation and fast security camera image analysis without network overhead.' },
                biocomputing: { title: 'Bio-computing', quadrant: 'Biotech & Convergent Tech', status: 'Scan', desc: 'Engineering DNA and biological cells for logical computation and data storage with high durability and near-zero energy consumption.', impact: 'Replacing massive data centers with millimeter-scale, eco-friendly big data storage systems.' },
                metaverse: { title: 'Metaverse & Spatial Computing', quadrant: 'Biotech & Convergent Tech', status: 'Assess', desc: 'Integrating VR, AR, and interactive 3D spaces for digital collaboration and professional simulators.', impact: 'Major shift in remote education, surgical simulation, and organizational digital twin creation.' }
            }
        },
        common: {
            envMaturity: 'Environment & Maturity:',
            symptoms: 'Organizational Signs & Behaviors:',
            examples: 'Industry Representatives:',
            keyTasks: 'Key Duties & Tools:',
            orgExample: 'Real Organizational Example:',
            sensing: 'Sensing',
            seizing: 'Seizing',
            transforming: 'Transforming'
        }
    }
});
