/**
 * EN — pages
 * @generated by scripts/split-locales.js
 */
registerLocale('en', {
    hub: {
        fitnessTitle: 'Future FITness & Readiness',
        fitnessDesc: 'Rohrbeck\'s maturity model, Perceiving / Prospecting / Probing simulation, 5-dimension self-assessment, and technology radar.',
        fitnessLink: 'Enter FITness Module',
        claTitle: 'Causal Layered Analysis (CLA)',
        claDesc: 'Inayatullah\'s four-layer deconstruction, interactive pyramid, scenario archive, and metaphor workshop.',
        claLink: 'Enter CLA Workshop',
        wheelTitle: 'Futures Wheel',
        wheelDesc: 'Cascading 1st–3rd order consequences; climate change radial tree, STEEP models, and 11-step process.',
        wheelLink: 'Enter Futures Wheel Simulator',
        backcastTitle: 'Backcasting & Reverse Mapping',
        backcastDesc: 'Normative future design and step-by-step reverse path from Robinson; vs. Forecasting and Tehran 1430 scenario.',
        backcastLink: 'Enter Backcasting Simulator'
    },
    integration: {
        step1Title: 'Scanning & Sensing (FITness)',
        step1Desc: 'Detect weak signals of change and assess organizational capacity to perceive and probe emerging opportunities.',
        step2Title: 'Root Cause & Deconstruction (CLA)',
        step2Desc: 'Break signals into systemic, discursive, and mythic layers to understand deep civilizational roots.',
        step3Title: 'Consequence Analysis (Futures Wheel)',
        step3Desc: 'Map 1st–3rd order cascading effects to identify secondary opportunities and threats.',
        step4Title: 'Reverse Transition Design (Backcasting)',
        step4Desc: 'Define a normative desired future and walk backward to today for actionable policy steps.'
    },
    depth: {
        tag: 'Methodological Depth',
        title: 'Why These Frameworks Complement Each Other',
        card1Title: 'From Signal to Structure',
        card1Desc: 'FITness scans weak signals; CLA moves them from news surface to structure and myth.',
        card2Title: 'From Cause to Consequence',
        card2Desc: 'The Futures Wheel visually maps cascading effects of structural changes.',
        card3Title: 'From Desired Future to Action',
        card3Desc: 'Backcasting works backward from a normative vision to define today\'s policy and operational steps.',
        card4Title: 'Organizational Learning Cycle',
        card4Desc: 'Together they form a strategic learning cycle: Sense → Understand → Map consequences → Design transition.'
    },
    fitnessDepth: {
        tag: 'Rohrbeck Theory Depth',
        title: 'The Perceiving → Prospecting → Probing Cycle',
        s1: 'Perceiving: Scan weak signals, analyze trends, and build environmental awareness.',
        s2: 'Prospecting: Scenario building, technology roadmapping, and designing plausible futures.',
        s3: 'Probing: Rapid prototyping, pilot projects, and validating assumptions.',
        s4: 'Transformation: Converting insights into structural, cultural, and organizational DNA change.'
    },
    claDepth: {
        tag: 'CLA Methodology Depth',
        title: 'Causal Layered Analysis Workshop Steps',
        s1: 'Select the issue and gather litany-layer data (news, statistics, events).',
        s2: 'Analyze systemic causes: policies, institutions, economic and technical incentives.',
        s3: 'Deconstruct discourses: worldviews, paradigms, and legitimizing narratives.',
        s4: 'Explore myth and metaphor: collective unconscious and transformative alternative metaphors.'
    },
    wheelDepth: {
        tag: 'Futures Wheel Execution Depth',
        title: 'Glenn\'s 11-Step Futures Wheel Process',
        s1: 'Define the central event/decision and assemble a multidisciplinary expert team.',
        s2: 'Brainstorm first-order consequences without judgment or censorship.',
        s3: 'Classify via STEEP and expand to second- and third-order effects.',
        s4: 'Prioritize, policy-design, and formulate defensive/adaptive action responses.'
    },
    bcDepth: {
        tag: 'Backcasting Depth',
        title: 'Robinson\'s 4-Step Backcasting Framework',
        s1: 'Vision the desired future: define normative indicators and target horizon.',
        s2: 'Gap analysis: measure distance between current structure and desired vision.',
        s3: 'Policy & regulation design: legal, financial, and technical transition tools.',
        s4: 'Adaptive roadmap: short-, medium-, and long-term actionable steps.'
    },
    citations: {
        portalBody: 'Eight teaching modules in this portal:<br>1. <strong>FITness</strong> — René Rohrbeck (<a href="https://rene-rohrbeck.com/about-foresight/" target="_blank" rel="noopener noreferrer">Corporate Foresight</a>, 2010)<br>2. <strong>CLA</strong> — Sohail Inayatullah (<a href="https://metafuture.org" target="_blank" rel="noopener noreferrer">Metafuture</a>)<br>3. <strong>Futures Wheel</strong> — Jerome C. Glenn (<a href="http://www.millennium-project.org" target="_blank" rel="noopener noreferrer">Millennium Project</a>)<br>4. <strong>Backcasting</strong> — John B. Robinson (<a href="https://www.sciencedirect.com/journal/energy-policy" target="_blank" rel="noopener noreferrer">Energy Policy</a>)<br>5. <strong>Popper Diamond</strong> — Rafael Popper (EU FORLEARN)<br>6. <strong>Six Pillars</strong> — Andy Hines & Peter Bishop<br>7. <strong>Scenario Planning</strong> — Shell / Peter Schwartz<br>8. <strong>Futurpreneurship</strong> — foresight × venture',
        fitnessTitle: 'Academic References & Organizational Maturity Sources:',
        fitnessBody: 'This assessment module is based on documented research by Professor René Rohrbeck at EDHEC Business School. Benchmark studies and findings on the 33% profitability advantage of foresight-driven organizations are available at <a href="https://rene-rohrbeck.com/about-foresight/" target="_blank" rel="noopener noreferrer">rene-rohrbeck.com</a> and his indexed publications on <a href="https://www.researchgate.net/profile/Rene-Rohrbeck" target="_blank" rel="noopener noreferrer">ResearchGate</a>.',
        claTitle: 'Academic Sources for Causal Layered Analysis:',
        claBody: 'Causal Layered Analysis (CLA) was developed by distinguished futurist Sohail Inayatullah. His theoretical and workshop case studies—including the reference book <a href="https://metafuture.org" target="_blank" rel="noopener noreferrer">The Causal Layered Analysis Reader</a> and articles on CLA 2.0 and 3.0—are indexed on <a href="https://metafuture.org" target="_blank" rel="noopener noreferrer">metafuture.org</a> and the <a href="https://research.usc.edu.au/" target="_blank" rel="noopener noreferrer">USC Research Bank</a>.',
        wheelTitle: 'Futures Wheel Methodology References:',
        wheelBody: 'The Futures Wheel methodology was first introduced by Jerome C. Glenn in 1971. Comprehensive guides on probability calculations and quantitative consequence mapping appear in <a href="http://www.millennium-project.org/publications-2/" target="_blank" rel="noopener noreferrer">Futures Research Methodology 3.0</a> by The Millennium Project, with the full chapter also available on <a href="https://www.researchgate.net/publication/349474778_THE_FUTURES_WHEEL" target="_blank" rel="noopener noreferrer">ResearchGate</a>.',
        backcastTitle: 'Academic Sources for Backcasting:',
        backcastBody: 'Normative backcasting was first formalized by <strong>John B. Robinson</strong> in 1982 for energy policy planning. Key works include <a href="https://www.sciencedirect.com/science/article/pii/030142158290059X" target="_blank" rel="noopener noreferrer">Energy Backcasting: A Proposed Method of Policy Analysis</a> in the journal <em>Energy Policy</em>, along with evolutionary participatory backcasting in sustainability literature. Urban resilience principles based on backcasting are also cited in foresight studies at the University of Copenhagen.'
    }
});
