/**
 * EN — wheel
 * @generated by scripts/split-locales.js
 */
registerLocale('en', Object.assign({
    wheelPage: {
        history: {
            accent: 'var(--color-wheel-red)',
            founderLabel: 'Founder',
            founder: 'Jerome C. Glenn',
            yearLabel: 'Year',
            year: '1972',
            institution: 'Millennium Project · AC/UNU',
            title: 'Origins of the Futures Wheel',
            origin: 'Jerome C. Glenn developed the Futures Wheel in 1971–1972 at the AC/UNU Millennium Project to map direct and indirect consequence chains from a central event. The phenomenon sits at the hub and experts draw 1st, 2nd, and 3rd order branches radially.',
            problemLabel: 'Problem',
            problem: 'Linear analysis examines a single event, but secondary, feedback, and long-range effects — often the decisive ones — stay hidden.',
            useLabel: 'Landmark applications',
            applications: 'Boeing\'s pilotless aircraft assessment, WHO and US DoD policy workshops, and Millennium Project hydropolitical crisis research.'
        },
        heroTag: 'Jerome Glenn',
        heroTitle: 'Interactive Futures Wheel Simulator',
        heroSub: 'Sequential causal consequence mapping — tracing 1st, 2nd, and 3rd order effects of Iran\'s climate crisis.',
        boeing: {
            title: 'Case Study: Boeing\'s Pilotless Passenger Aircraft Assessment',
            intro: 'Boeing used a Structured Futures Wheel to assess fully autonomous commercial aircraft through 2045:',
            cards: [
                { title: '1st Order (Direct Effects)', body: 'Eliminating pilot human error, reducing crew costs, and optimizing fuel via real-time flight algorithms.' },
                { title: '2nd Order (Secondary Effects)', body: 'Lower ticket prices, pilot layoffs, union resistance, and new cyber-attack threats to aircraft.' },
                { title: '3rd Order (Long-Term Effects)', body: 'Complex liability law challenges and passengers\' psychological resistance to trusting machines with their lives.' }
            ],
            lesson: '<strong>Strategic lesson:</strong> the biggest challenge was not technology but societal psychology and legal liability (3rd order); investment shifted toward adaptive semi-autonomous systems.'
        },
        boeingTitle: 'Case Study: Boeing\'s Pilotless Passenger Aircraft Assessment',
        boeingIntro: 'Boeing used a Structured Futures Wheel to assess fully autonomous commercial aircraft through 2045:',
        boeingO1: '1st Order (Direct Effects)',
        boeingO1Text: 'Eliminating pilot human error, reducing crew costs, and optimizing fuel via real-time flight algorithms.',
        boeingO2: '2nd Order (Secondary Effects)',
        boeingO2Text: 'Lower ticket prices, pilot layoffs, union resistance, and new cyber-attack threats to aircraft.',
        boeingO3: '3rd Order (Long-Term Effects)',
        boeingO3Text: 'Complex liability law challenges and passengers\' psychological resistance to trusting machines with their lives.',
        boeingLesson: '<strong>Strategic lesson:</strong> the biggest challenge was not technology but societal psychology and legal liability (3rd order); investment shifted toward adaptive semi-autonomous systems.',
        diagramTitle: 'Climate Security Consequences — Reference Diagram',
        diagramP1: 'Stepwise structure of 1st order (drought, dust storms, heat waves), 2nd order (aquifer depletion, farmer livelihoods, migration), and 3rd order national-security effects.',
        diagramP2: 'Systematic analysis reveals feedback loops, cross-effects, and border defense strain — enabling national resilience solutions.',
        modelsTag: 'Extended Methodology',
        modelsTitle: 'Futures Wheel Model Variants',
        modelsSub: 'Beyond a simple diagram — four key modeling approaches in advanced projects.',
        tabClassic: 'Classic Model',
        tabStructured: 'Structured STEEP',
        tabQuantitative: 'Quantitative Model',
        tabAction: 'Policy-Oriented',
        processTag: 'Execution Process',
        processTitle: '11 Steps to Draw & Run a Futures Wheel',
        detailFocus: 'Primary Focus',
        detailTool: 'Execution Method',
        detailOutput: 'Real-World Example',
        steps: [
            { title: 'Define the Central Issue', desc: 'Clearly state the origin event at the hub center and set temporal/spatial boundaries.' },
            { title: 'Assemble Expert Panel (Delphi)', desc: 'Recruit interdisciplinary experts to reduce bias and groupthink.' },
            { title: 'Identify 1st-Order Consequences', desc: 'Brainstorm: "What immediate technical, environmental, or social effects occur?"' },
            { title: 'Screen & Select Consequences', desc: 'Filter by correlation and impact strength; remove redundancy.' },
            { title: 'Extract 2nd-Order Consequences', desc: 'For each 1st-order node: "What is the next secondary reaction?"' },
            { title: 'Extract 3rd-Order Consequences', desc: 'Trace chains to long-range security, identity, and systemic collapse effects.' },
            { title: 'Map Network & Cross-Links', desc: 'Discover feedback loops and amplifying cross-branch relationships.' },
            { title: 'Quantify & Cross-Analyze', desc: 'Estimate probability and impact to identify highest-risk paths.' },
            { title: 'Policy & Response Design', desc: 'Attach Policy Response Nodes to negative outcomes for an action roadmap.' },
            { title: 'Delphi Validation Round', desc: 'Independent expert review to reduce availability heuristic bias.' },
            { title: 'Continuous Monitoring', desc: 'Define KPIs and periodically refresh the wheel with new weak signals.' }
        ]
    },
    wheelModels: {
        classic: {
            title: 'Classic Futures Wheel (Jerome Glenn Model)',
            desc: 'Introduced in 1971 by Jerome C. Glenn (Millennium Project), this model relies on creative brainstorming and free exploration without preset categories. The central phenomenon sits at the hub and experts draw radial consequence chains.',
            focus: 'Creative brainstorming and open, multi-directional mapping of direct and indirect qualitative consequences.',
            tool: 'Live workshops or digital platforms (Miro/Mural) with connected color-coded cards.',
            output: 'US DoD / GE assessment of internet and IT impacts on US Army operations in the late 1970s.'
        },
        structured: {
            title: 'Structured STEEP Futures Wheel',
            desc: 'To prevent one-dimensional analysis, the wheel is segmented by STEEP variables (Social, Technological, Economic, Environmental, Political). Each consequence is placed in its sector and grows secondary and tertiary branches.',
            focus: 'Systematic classification for cross-analysis of macro environmental and technological trends.',
            tool: 'Divide the canvas into 5–6 STEEP sectors and run focused brainstorm panels per sector.',
            output: 'WHO study mapping pandemic and lifestyle change consequences through 2040.'
        },
        quantitative: {
            title: 'Quantitative Futures Wheel',
            desc: 'In rigorous foresight projects, the wheel integrates probability and impact scoring. Experts rate each node for probability (0–1) and impact/desirability (−10 to +10) to identify critical risk paths.',
            focus: 'Numerical estimation, mathematical prioritization of threats, and strategic path valuation.',
            tool: 'Probabilistic Delphi surveys, statistical simulation, and risk matrix algorithms.',
            output: 'Millennium Project research on MENA hydropolitical crises and water-scarcity security collapse paths.'
        },
        action: {
            title: 'Policy-Oriented Futures Wheel',
            desc: 'Rather than merely describing the future, this model drives action. At the end of negative chains, experts attach Policy Response Nodes, converting the wheel into an operational roadmap.',
            focus: 'Concrete countermeasures, civil defense, adaptive strategies, and mitigation design.',
            tool: 'Executive strategy workshops, defensive scenario planning, and war-gaming exercises.',
            output: 'Finland MoD cyber-defense plan linking response protocols to Baltic port and supply-chain attack scenarios.'
        }
    }
}, {
    wheelWorkshop: {
        modeDemo: 'Tutorial Example',
        modeWorkshop: 'Interactive Workshop',
        title: 'Build Your Futures Wheel',
        sub: 'Enter the central issue and consequences for each order — the wheel draws automatically.',
        hubLabel: 'Central issue / event',
        hubPlaceholder: 'e.g. AI in higher education',
        hubSubLabel: 'Short note (optional)',
        hubSubPlaceholder: 'e.g. LLM adoption in universities',
        branchesTitle: '1st-order consequences',
        addBranch: 'Add branch',
        build: 'Draw wheel',
        loadDemo: 'Load climate example',
        cascadeHint: 'Click any 1st-order consequence to see details in the sidebar.',
        sidebarSub: 'Select a 1st-order consequence to highlight its 2nd and 3rd order chain.',
        hubTag: 'Central issue',
        branchPlaceholder: '1st-order consequence',
        descPlaceholder: 'Short description (optional)',
        addOrder2: 'Add 2nd order',
        addOrder3: 'Add 3rd order',
        order2Placeholder: '2nd-order consequence',
        order3Placeholder: '3rd-order consequence',
        remove: 'Remove',
        noChain: 'No 2nd/3rd order added',
        errHub: 'Please enter a central issue.',
        errBranch: 'Add at least one 1st-order consequence with a title.'
    }
}));
