/**
 * One-time utility: split combined i18n-*.js into js/locales/fa|en/*.js
 * Run: node scripts/split-locales.js
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');

function extractAssignBlocks(content, lang) {
    const marker = `Object.assign(I18N.${lang}, `;
    const blocks = [];
    let i = 0;
    while (i < content.length) {
        const start = content.indexOf(marker, i);
        if (start === -1) break;
        let depth = 0;
        let j = start + marker.length;
        if (content[j] !== '{') { i = j; continue; }
        const objStart = j;
        for (; j < content.length; j++) {
            const c = content[j];
            if (c === '{') depth++;
            else if (c === '}') {
                depth--;
                if (depth === 0) {
                    blocks.push(content.slice(objStart, j + 1));
                    i = j + 1;
                    break;
                }
            }
        }
    }
    return blocks;
}

function mergeBlocks(blocks) {
    if (!blocks.length) return '{}';
    if (blocks.length === 1) return blocks[0];
    return `Object.assign(${blocks.join(', ')})`;
}

function writeLocale(lang, name, objLiteral) {
    const dir = path.join(ROOT, 'js', 'locales', lang);
    fs.mkdirSync(dir, { recursive: true });
    const file = path.join(dir, `${name}.js`);
    const body = `/**
 * ${lang.toUpperCase()} — ${name}
 * @generated by scripts/split-locales.js
 */
registerLocale('${lang}', ${objLiteral});
`;
    fs.writeFileSync(file, body, 'utf8');
    console.log('Wrote', file);
}

// i18n.js inline fa/en
const i18nCore = fs.readFileSync(path.join(ROOT, 'i18n.js'), 'utf8');
const faCoreMatch = i18nCore.match(/fa:\s*(\{[\s\S]*?\})\s*,\s*en:/);
const enCoreMatch = i18nCore.match(/en:\s*(\{[\s\S]*?\})\s*\}\s*;/);
if (faCoreMatch && enCoreMatch) {
    writeLocale('fa', 'common', faCoreMatch[1]);
    writeLocale('en', 'common', enCoreMatch[1]);
}

const sources = [
    { file: 'i18n-pages.js', name: 'pages' },
    { file: 'i18n-fitness.js', name: 'fitness' },
    { file: 'i18n-cla.js', name: 'cla' },
    { file: 'i18n-backcast.js', name: 'backcast' },
    { file: 'i18n-wheel.js', name: 'wheel' },
];

for (const { file, name } of sources) {
    const fp = path.join(ROOT, file);
    if (!fs.existsSync(fp)) continue;
    const content = fs.readFileSync(fp, 'utf8');
    const faBlocks = extractAssignBlocks(content, 'fa');
    const enBlocks = extractAssignBlocks(content, 'en');
    writeLocale('fa', name, mergeBlocks(faBlocks));
    writeLocale('en', name, mergeBlocks(enBlocks));
}

// Brand locale stubs
const brandFa = `registerLocale('fa', {
    brand: {
        tag: 'پرسونال برند',
        heroTitle: 'علی منصوری',
        heroSub: 'پژوهشگر آینده‌پژوهی استراتژیک · دانشجوی دکتری دانشگاه تهران · طراح ابزارهای تعاملی foresight',
        aboutLink: 'درباره من',
        articlesLink: 'مقالات و یادداشت‌ها',
        methodsLink: 'ابزارهای آموزشی',
        bioTitle: 'معرفی',
        bioP1: 'من <strong>علی منصوری</strong> هستم؛ دانشجوی دکتری آینده‌پژوهی در دانشگاه تهران. این پورتال هم فضای تدریس و آموزش متدهای foresight است و هم <strong>پرسونال برند</strong> من — جایی برای معرفی کارها، انتشار مقالات و اشتراک تجربه‌های پژوهشی.',
        bioP2: 'تمرکز من بر ترکیب نظریه‌های کلاسیک (روهربک، عنایت‌الله، گلن، رابینسون) با ابزارهای تعاملی وب است تا یادگیری آینده‌پژوهی برای دانشجو، مدیر و علاقه‌مند، عملی و قابل لمس شود.',
        focusTitle: 'حوزه‌های تمرکز',
        focuses: [
            { icon: 'compass', title: 'آینده‌پژوهی سازمانی', desc: 'بلوغ foresight، FITness و رادار فناوری' },
            { icon: 'layers', title: 'تحلیل گفتمانی و CLA', desc: 'واسازی لایه‌ای مسائل کلان و سیاستی' },
            { icon: 'pen-line', title: 'نشر علمی و مقاله', desc: 'یادداشت‌های پژوهشی و مقالات آینده‌پژوهی' },
            { icon: 'code-2', title: 'طراحی ابزار تعاملی', desc: 'تبدیل متدولوژی به محیط کارگاهی دیجیتال' }
        ],
        ctaResume: 'رزومه کامل',
        ctaMethods: 'ورود به ابزارها'
    },
    aboutPage: {
        tag: 'درباره من',
        title: 'علی منصوری — آینده‌پژوه و سازنده ابزار',
        sub: 'ترکیب پژوهش آکادمیک، تدریس و طراحی تجربه تعاملی برای foresight',
        missionTitle: 'ماموریت',
        mission: 'ساختن پلی میان نظریه آینده‌پژوهی و عمل — برای دانشجویان، سازمان‌ها و تصمیم‌سازانی که می‌خواهند آینده را نه فقط پیش‌بینی کنند، بلکه <strong>طراحی</strong> کنند.',
        eduTitle: 'تحصیلات',
        edu: 'دکتری آینده‌پژوهی — دانشگاه تهران',
        contactTitle: 'ارتباط',
        contact: 'رزومه و پروفایل حرفه‌ای در لینک زیر'
    },
    articlesPage: {
        tag: 'مقالات',
        title: 'یادداشت‌ها و مقالات',
        sub: 'فهرست مقالات و یادداشت‌های پژوهشی — به‌زودی مقالات جدید اضافه می‌شوند.',
        emptyTitle: 'به‌زودی',
        emptyDesc: 'اولین مقالات در حال آماده‌سازی هستند. برای دنبال کردن به‌روزرسانی‌ها رزومه و مخزن GitHub را ببینید.',
        sampleArticles: [
            { date: '۱۴۰۴', title: 'چرا FITness روهربک هنوز اهمیت دارد؟', tag: 'سازمانی', status: 'draft' },
            { date: '۱۴۰۴', title: 'CLA در سیاست‌گذاری ملی: درس از سنگاپور', tag: 'CLA', status: 'draft' },
            { date: '۱۴۰۳', title: 'از Litany تا Myth — راهنمای عملی کارگاه CLA', tag: 'آموزشی', status: 'draft' }
        ]
    }
});`;

const brandEn = `registerLocale('en', {
    brand: {
        tag: 'Personal Brand',
        heroTitle: 'Ali Mansouri',
        heroSub: 'Strategic Foresight Researcher · PhD Candidate, University of Tehran · Builder of interactive foresight tools',
        aboutLink: 'About Me',
        articlesLink: 'Articles & Notes',
        methodsLink: 'Teaching Tools',
        bioTitle: 'Introduction',
        bioP1: 'I am <strong>Ali Mansouri</strong>, a PhD candidate in Foresight at the University of Tehran. This portal is both my <strong>teaching lab</strong> for foresight methods and my <strong>personal brand</strong> — a place to introduce my work, publish articles, and share research insights.',
        bioP2: 'I focus on combining classic theory (Rohrbeck, Inayatullah, Glenn, Robinson) with interactive web tools so foresight learning becomes tangible for students, managers, and curious practitioners.',
        focusTitle: 'Focus Areas',
        focuses: [
            { icon: 'compass', title: 'Corporate Foresight', desc: 'Maturity models, FITness, technology radar' },
            { icon: 'layers', title: 'CLA & Discourse', desc: 'Layered analysis of macro and policy issues' },
            { icon: 'pen-line', title: 'Publishing', desc: 'Research notes and foresight articles' },
            { icon: 'code-2', title: 'Interactive Tools', desc: 'Turning methodology into digital workshops' }
        ],
        ctaResume: 'Full Resume',
        ctaMethods: 'Explore Tools'
    },
    aboutPage: {
        tag: 'About',
        title: 'Ali Mansouri — Foresight Researcher & Tool Builder',
        sub: 'Bridging academic research, teaching, and interactive foresight experiences',
        missionTitle: 'Mission',
        mission: 'Build a bridge between foresight theory and practice — for students, organizations, and decision-makers who want to <strong>design</strong> futures, not only predict them.',
        eduTitle: 'Education',
        edu: 'PhD in Foresight — University of Tehran',
        contactTitle: 'Connect',
        contact: 'Professional profile and resume at the link below'
    },
    articlesPage: {
        tag: 'Articles',
        title: 'Notes & Articles',
        sub: 'Research notes and articles — new posts coming soon.',
        emptyTitle: 'Coming Soon',
        emptyDesc: 'First articles are in preparation. Follow updates via resume and GitHub repository.',
        sampleArticles: [
            { date: '2025', title: 'Why Rohrbeck FITness Still Matters', tag: 'Corporate', status: 'draft' },
            { date: '2025', title: 'CLA in National Policy: Lessons from Singapore', tag: 'CLA', status: 'draft' },
            { date: '2024', title: 'From Litany to Myth — A Practical CLA Workshop Guide', tag: 'Teaching', status: 'draft' }
        ]
    }
});`;

fs.mkdirSync(path.join(ROOT, 'js', 'locales', 'fa'), { recursive: true });
fs.mkdirSync(path.join(ROOT, 'js', 'locales', 'en'), { recursive: true });
fs.writeFileSync(path.join(ROOT, 'js', 'locales', 'fa', 'brand.js'), `/** FA brand */\n${brandFa}\n`);
fs.writeFileSync(path.join(ROOT, 'js', 'locales', 'en', 'brand.js'), `/** EN brand */\n${brandEn}\n`);
console.log('Wrote brand locale files');
