/**
 * FA · common
 * @generated by scripts/split-locales.js
 */
registerLocale('fa', {
        lang: { label: 'English', switch: 'EN' },
        nav: {
            home: 'خانه',
            about: 'درباره',
            articles: 'مقالات',
            methods: 'روش‌های آینده‌پژوهی',
            cv: 'رزومه',
            fitness: 'آمادگی و تناسب (FITness)',
            cla: 'تحلیل لایه‌ای علت‌ها (CLA)',
            wheel: 'چرخ آینده (Futures Wheel)',
            backcast: 'پس‌نگری (Backcasting)',
            assess: 'ارزیابی بلوغ سازمان',
            menu: 'منو'
        },
        footer: {
            desc: 'فضای شخصی علی منصوری برای آینده‌پژوهی راهبردی · متد، کارگاه و یادداشت · دانشگاه تهران',
            descBackcast: 'فضای شخصی علی منصوری برای آینده‌پژوهی راهبردی · متد، کارگاه و یادداشت · دانشگاه تهران',
            descWheel: 'فضای شخصی علی منصوری برای آینده‌پژوهی راهبردی · متد، کارگاه و یادداشت · دانشگاه تهران',
            role: 'دانشجوی دکتری آینده‌پژوهی · دانشگاه تهران',
            resume: 'رزومه',
            copyright: '© علی منصوری · FORESIGHT HUB'
        },
        index: {
            badge: 'معماری سیستم + آینده‌پژوهی راهبردی',
            heroTitleHtml: 'سلام، من <span class="home-hero-name">علی منصوری‌ام</span>.',
            heroBridge: 'سناریوهای آینده را به زیرساختی وصل می‌کنم که باید از دل سخت‌ترین فشارهای واقعی، زنده و سالم بیرون بیاید.',
            credentialPhd: 'دانشجوی دکتری آینده‌پژوهی · دانشگاه تهران',
            credentialSnapp: 'معمار راه‌حل سامانه‌های ابری · اسنپ',
            ctaCollab: 'دعوت برای تدریس / مشاوره',
            ctaMethods: 'روش‌های آینده‌پژوهی',
            mailCta: 'ارتباط مستقیم',
            contactEmailCta: 'ارسال ایمیل برای هماهنگی و گفت‌وگو'
        },
        common: {
            close: 'بستن',
            readMore: 'بیشتر بدانید',
            order1: 'مرتبه ۱',
            order2: 'مرتبه ۲',
            order3: 'مرتبه ۳',
            clickExplore: 'برای کاوش کلیک کنید',
            scrollHint: 'برای مشاهده کامل، اسکرول کنید',
            tracks: {
                label: 'مسیر اجرا',
                university: 'دانشگاه',
                industry: 'صنعت و سازمان',
                workshop: 'کارگاه تعاملی',
                universitySection: 'مسیر دانشگاه · طرح درس و تدریس',
                industrySection: 'مسیر صنعت · استقرار در سازمان',
                workshopSection: 'کارگاه تعاملی',
                labelRole: 'نقش',
                labelJob: 'وظیفه',
                agendaTitle: 'دستور کار کارگاه',
                stakeholdersTitle: 'ذی‌نفعان',
                deliverablesTitle: 'خروجی‌ها',
                workflowTitle: 'جریان کار',
                checklistTitle: 'چک‌لیست',
                boardMemoTitle: 'یادداشت هیئت‌مدیره',
                facilitatorTitle: 'نکات تسهیل‌گر'
            }
        },
        wheel: {
            hubLabel: 'تغییر اقلیم در ایران',
            hubSub: '(کاهش بارش و افزایش دما)',
            sidebarTitle: 'شبکه پیامدها و تاثیرات پنهان',
            sidebarSub: 'یکی از پیامدهای مرتبه اول را در شبکه دایره‌ای انتخاب کنید تا تاثیرات ثانویه و پیامدهای نهایی آن نمایش داده شود.',
            chain2: 'پیامدهای مرتبه دوم',
            chain3: 'پیامدهای مرتبه سوم'
        },
        cla: {
            layers: {
                litany: 'لیتانی (Litany)',
                systemic: 'علل اجتماعی و ساختاری (Systemic)',
                worldview: 'گفتمان و جهان‌بینی (Worldview)',
                myth: 'اسطوره و استعاره (Myth)'
            }
        },
        radar: {
            defaultTitle: 'رادار فناوری‌های نوظهور',
            defaultSub: 'روی نقاط درخشان کلیک کنید تا جزئیات فناوری وضعیت بلوغ و توصیه استراتژیک نمایش داده شود.',
            status: 'وضعیت رادار:',
            impact: 'تاثیر استراتژیک بر سازمان:'
        }
    });
