/**
 * FA — common
 * @generated by scripts/split-locales.js
 */
registerLocale('fa', {
        lang: { label: 'English', switch: 'EN' },
        nav: {
            home: 'صفحه نخست',
            about: 'درباره من',
            articles: 'مقالات',
            methods: 'متدها',
            fitness: 'آمادگی و تناسب (FITness)',
            cla: 'تحلیل لایه‌ای علت‌ها (CLA)',
            wheel: 'چرخ آینده (Futures Wheel)',
            backcast: 'پس‌نگری (Backcasting)',
            assess: 'ارزیابی بلوغ سازمان',
            menu: 'منو'
        },
        footer: {
            desc: 'علی منصوری، دانشجوی دکتری آینده‌پژوهی، دانشگاه تهران.',
            descBackcast: 'علی منصوری، دانشجوی دکتری آینده‌پژوهی، دانشگاه تهران.',
            descWheel: 'علی منصوری، دانشجوی دکتری آینده‌پژوهی، دانشگاه تهران.',
            role: 'دانشجوی دکتری آینده‌پژوهی، دانشگاه تهران',
            resume: 'رزومه',
            copyright: '© علی منصوری'
        },
        index: {
            badge: 'علی منصوری',
            heroTitle: 'STRATEGIC FORESIGHT<br>HUB',
            heroSub: 'دانشجوی دکتری آینده‌پژوهی، دانشگاه تهران. درباره آینده‌های محتمل می‌نویسم، روی متدهای foresight کار می‌کنم، و ابزارهایش را طراحی می‌کنم.',
            ctaMethods: 'متدها'
        },
        common: {
            close: 'بستن',
            readMore: 'بیشتر بدانید',
            order1: 'مرتبه ۱',
            order2: 'مرتبه ۲',
            order3: 'مرتبه ۳',
            clickExplore: 'برای کاوش کلیک کنید',
            scrollHint: 'برای مشاهده کامل، اسکرول کنید'
        },
        wheel: {
            hubLabel: 'تغییر اقلیم در ایران',
            hubSub: '(کاهش بارش و افزایش دما)',
            sidebarTitle: 'شبکه پیامدها و تاثیرات پنهان',
            sidebarSub: 'یکی از پیامدهای مرتبه اول را در شبکه دایره‌ای انتخاب کنید تا تاثیرات ثانویه و پیامدهای نهایی آن نمایش داده شود.',
            chain2: 'پیامدهای مرتبه دوم',
            chain3: 'پیامدهای مرتبه سوم'
        },
        cla: {
            layers: {
                litany: 'لیتانی (Litany)',
                systemic: 'علل اجتماعی و ساختاری (Systemic)',
                worldview: 'گفتمان و جهان‌بینی (Worldview)',
                myth: 'اسطوره و استعاره (Myth)'
            }
        },
        radar: {
            defaultTitle: 'رادار فناوری‌های نوظهور',
            defaultSub: 'روی نقاط درخشان کلیک کنید تا جزئیات فناوری، وضعیت بلوغ و توصیه استراتژیک نمایش داده شود.',
            status: 'وضعیت رادار:',
            impact: 'تاثیر استراتژیک بر سازمان:'
        }
    });
