/**
 * FA · pages
 * @generated by scripts/split-locales.js
 */
registerLocale('fa', {
    hub: {
        fitnessTitle: 'آمادگی و تناسب با آینده (FITness)',
        fitnessDesc: 'بررسی مدل بلوغ رنه روهربک، شبیه‌سازی Perceiving / Prospecting / Probing، تست خودارزیابی ۵ بعدی و رادار فناوری.',
        fitnessLink: 'ورود به بخش تناسب آینده',
        claTitle: 'تحلیل لایه‌ای علت‌ها (CLA)',
        claDesc: 'مدل سهیل عنایت‌الله برای نفوذ به لایه‌های چهارگانه مسائل، هرم تعاملی، آرشیو سناریوها و کارگاه استعاره.',
        claLink: 'ورود به کارگاه CLA',
        wheelTitle: 'چرخ آینده (Futures Wheel)',
        wheelDesc: 'نگاشت زنجیره‌ای پیامدهای مرتبه اول تا سوم؛ درخت شعاعی تغییر اقلیم، مدل‌های STEEP و فرآیند ۱۱ مرحله‌ای.',
        wheelLink: 'ورود به شبیه‌ساز چرخ آینده',
        backcastTitle: 'پس‌نگری و نگاشت معکوس (Backcasting)',
        backcastDesc: 'طراحی آرمان‌شهر و بازگشت گام‌به‌گام به حال بر مبنای جان رابینسون؛ مقایسه با Forecasting و سناریوی تهران ۱۴۳۰.',
        backcastLink: 'ورود به شبیه‌ساز پس‌نگری'
    },
    integration: {
        step1Title: 'رصد و حس‌گری (FITness)',
        step1Desc: 'شناسایی سیگنال‌های ضعیف تغییر و ارزیابی توان سازمانی برای درک و آزمایش فرصت‌های نوظهور.',
        step2Title: 'ریشه‌یابی و واسازی (CLA)',
        step2Desc: 'شکستن سیگنال‌ها به لایه‌های سیستمی، گفتمانی و اسطوره‌ای برای درک ریشه‌های عمیق مسئله.',
        step3Title: 'تحلیل پیامدها (Futures Wheel)',
        step3Desc: 'نگاشت پیامدهای زنجیره‌ای مرتبه اول تا سوم برای شناسایی فرصت‌ها و تهدیدهای ثانویه.',
        step4Title: 'طراحی گذار معکوس (Backcasting)',
        step4Desc: 'تعریف چشم‌انداز هنجاری مطلوب و بازگشت گام‌به‌گام به حال برای تدوین سیاست‌های اجرایی.'
    },
    depth: {
        tag: 'عمق متدولوژیک',
        title: 'چرا این چارچوب‌ها مکمل یکدیگرند؟',
        card1Title: 'از سیگنال تا ساختار',
        card1Desc: 'FITness سیگنال‌های ضعیف را رصد می‌کند؛ CLA آن‌ها را از سطح اخبار به ساختار و اسطوره می‌برد.',
        card2Title: 'از علت تا پیامد',
        card2Desc: 'Futures Wheel پیامدهای زنجیره‌ای تغییرات ساختاری را به صورت بصری و سیستمی نگاشت می‌کند.',
        card3Title: 'از آینده مطلوب تا اقدام',
        card3Desc: 'Backcasting از تصویر آینده مطلوب به عقب برمی‌گردد و گام‌های سیاستی و عملیاتی امروز را مشخص می‌کند.',
        card4Title: 'چرخه یادگیری سازمانی',
        card4Desc: 'ترکیب این ابزارها یک چرخه یادگیری استراتژیک می‌سازد: حس → فهم → پیش‌بینی پیامد → طراحی گذار.'
    },
    fitnessDepth: {
        tag: 'عمق نظریه روهربک',
        title: 'چرخه سه‌گانه Perceiving → Prospecting → Probing',
        s1: 'درک (Perceiving): رصد سیگنال‌های ضعیف، تحلیل روندها و ساخت آگاهی محیطی.',
        s2: 'کاوش (Prospecting): سناریوسازی، نقشه‌راه فناوری و طراحی آینده‌های محتمل.',
        s3: 'آزمایش (Probing): نمونه‌سازی سریع، پروژه‌های پایلوت و اعتبارسنجی فرضیات.',
        s4: 'تحول (Transformation): تبدیل بینش‌ها به تغییر ساختاری، فرهنگی و DNA سازمانی.'
    },
    claDepth: {
        tag: 'عمق متدولوژی CLA',
        title: 'گام‌های کارگاه تحلیل لایه‌ای علت‌ها',
        s1: 'انتخاب مسئله و جمع‌آوری داده‌های لایه لیتانی (اخبار، آمار، رویدادها).',
        s2: 'تحلیل علل ساختاری: سیاست‌ها، نهادها، مشوق‌های اقتصادی و فنی.',
        s3: 'واسازی گفتمان‌ها: جهان‌بینی‌ها، پارادایم‌ها و روایت‌های مشروعیت‌بخش.',
        s4: 'کاوش اسطوره و استعاره: ناخودآگاه جمعی و خلق استعاره‌های تحول‌آفرین.'
    },
    wheelDepth: {
        tag: 'عمق اجرای چرخ آینده',
        title: 'فرآیند ۱۱ مرحله‌ای Glenn Futures Wheel',
        s1: 'تعریف رویداد/تصمیم محوری و تشکیل تیم خبرگان چندتخصصی.',
        s2: 'طوفان فکری پیامدهای مرتبه اول بدون قضاوت و سانسور.',
        s3: 'طبقه‌بندی STEEP و گسترش به پیامدهای مرتبه دوم و سوم.',
        s4: 'اولویت‌بندی، سیاست‌گذاری و تدوین اقدامات پدافندی/انطباقی.'
    },
    bcDepth: {
        tag: 'عمق پس‌نگری',
        title: 'چارچوب ۴ گانه Robinson Backcasting',
        s1: 'تصویرسازی آینده مطلوب: تعریف شاخص‌های هنجاری و چشم‌انداز هدف.',
        s2: 'تحلیل شکاف (Gap Analysis): فاصله ساختار فعلی با تصویر مطلوب.',
        s3: 'طراحی سیاست و مقررات: ابزارهای قانونی، مالی و فنی گذار.',
        s4: 'نقشه راه انطباقی: اقدامات کوتاه‌مدت، میان‌مدت و بلندمدت.'
    },
    citations: {
        portalBody: 'هشت ماژول آموزشی این پورتال:<br>۱. <strong>FITness</strong> · رنه روهربک (<a href="https://rene-rohrbeck.com/about-foresight/" target="_blank" rel="noopener noreferrer">Corporate Foresight</a>, 2010)<br>۲. <strong>CLA</strong> · سهیل عنایت‌الله (<a href="https://metafuture.org" target="_blank" rel="noopener noreferrer">Metafuture</a>)<br>۳. <strong>Futures Wheel</strong> · جروم گلن (<a href="http://www.millennium-project.org" target="_blank" rel="noopener noreferrer">Millennium Project</a>)<br>۴. <strong>Backcasting</strong> · جان رابینسون (<a href="https://www.sciencedirect.com/journal/energy-policy" target="_blank" rel="noopener noreferrer">Energy Policy</a>)<br>۵. <strong>Popper Diamond</strong> · رافائل پوپر (EU FORLEARN)<br>۶. <strong>Six Pillars</strong> · Andy Hines & Peter Bishop<br>۷. <strong>Scenario Planning</strong> · Shell / Peter Schwartz<br>۸. <strong>Futurpreneurship</strong> · foresight × venture',
        fitnessTitle: 'ارجاع علمی و منابع مطالعه بلوغ سازمانی:',
        fitnessBody: 'این بخش ارزیابی و مفاهیم بر اساس پژوهش‌های مستند پروفسور رنه روهربک در EDHEC Business School توسعه داده شده است. مطالعات بنچ‌مارک و یافته‌های آماری سودآوری ۳۳ درصدی سازمان‌های آینده‌نگر را می‌توانید در <a href="https://rene-rohrbeck.com/about-foresight/" target="_blank" rel="noopener noreferrer">rene-rohrbeck.com</a> و مقالات نمایه شده او در <a href="https://www.researchgate.net/profile/Rene-Rohrbeck" target="_blank" rel="noopener noreferrer">ResearchGate</a> دنبال کنید.',
        claTitle: 'منابع علمی تحلیل لایه‌ای علت‌ها:',
        claBody: 'روش تحلیل لایه‌ای علت‌ها (CLA) توسط آینده‌پژوه برجسته سهیل عنایت‌الله ابداع گردید. کتاب‌ها و مطالعات موردی تئوری و کارگاهی او از جمله کتاب مرجع <a href="https://metafuture.org" target="_blank" rel="noopener noreferrer">The Causal Layered Analysis Reader</a> و مقالات نوین در حوزه CLA 2.0 و 3.0 در وبگاه رسمی او در <a href="https://metafuture.org" target="_blank" rel="noopener noreferrer">metafuture.org</a> و مخزن پژوهشی <a href="https://research.usc.edu.au/" target="_blank" rel="noopener noreferrer">USC Research Bank</a> نمایه شده است.',
        wheelTitle: 'مرجع متدولوژی و مطالعه روش‌شناختی چرخ آینده:',
        wheelBody: 'متدولوژی چرخ آینده ابتدا توسط جروم سی. گلن در سال ۱۹۷۱ معرفی گردید. راهنما و فصول جامع نحوه محاسبات احتمالات و کمی‌سازی پیامدها در نشریه مرجع <a href="http://www.millennium-project.org/publications-2/" target="_blank" rel="noopener noreferrer">Futures Research Methodology 3.0</a> توسط پروژه هزاره (The Millennium Project) منتشر گردیده و فصل کامل آن در <a href="https://www.researchgate.net/publication/349474778_THE_FUTURES_WHEEL" target="_blank" rel="noopener noreferrer">ResearchGate</a> در دسترس است.',
        backcastTitle: 'منابع علمی روش پس‌نگری (Backcasting):',
        backcastBody: 'روش پس‌نگری هنجاری به عنوان متدولوژی مقابله با روندهای تحمیلی گذشته، اولین بار به شکل منسجم توسط <strong>جان بی. رابینسون (John B. Robinson)</strong> در سال ۱۹۸۲ برای برنامه‌ریزی سیاست‌های انرژی معرفی شد. کتاب‌ها و مقالات برجسته او از جمله <a href="https://www.sciencedirect.com/science/article/pii/030142158290059X" target="_blank" rel="noopener noreferrer">Energy Backcasting: A Proposed Method of Policy Analysis</a> در نشریه معتبر <em>Energy Policy</em> و اصول تکاملی روش‌شناختی پس‌نگری مشارکتی در نشریات توسعه پایدار نمایه شده است. همچنین اصول تاب‌آوری شهری بر مبنای پس‌نگری در مطالعات دپارتمان آینده‌پژوهی دانشگاه کپنهاگ مورد استناد است.'
    }
});
